/**
 * Generated by Gas3 v1.0.1 (Granite Data Services) on Fri Mar 14 16:48:03 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Principal.as).
 */

package ch.ess.tt.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class PrincipalBase implements IExternalizable {

        private var _admin:Boolean;
        private var _email:String;
        private var _enabled:Boolean;
        private var _firstName:String;
        private var _id:int;
        private var _locale:String;
        private var _name:String;
        private var _oe:String;
        private var _passwordHash:String;
        private var _roleAuthor:Boolean;
        private var _roleDeveloper:Boolean;
        private var _roleTester:Boolean;
        private var _userName:String;

        public function set admin(value:Boolean):void {
            _admin = value;
        }
        public function get admin():Boolean {
            return _admin;
        }

        public function set email(value:String):void {
            _email = value;
        }
        public function get email():String {
            return _email;
        }

        public function set enabled(value:Boolean):void {
            _enabled = value;
        }
        public function get enabled():Boolean {
            return _enabled;
        }

        public function set firstName(value:String):void {
            _firstName = value;
        }
        public function get firstName():String {
            return _firstName;
        }

        public function set id(value:int):void {
            _id = value;
        }
        public function get id():int {
            return _id;
        }

        public function set locale(value:String):void {
            _locale = value;
        }
        public function get locale():String {
            return _locale;
        }

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function set oe(value:String):void {
            _oe = value;
        }
        public function get oe():String {
            return _oe;
        }

        public function set passwordHash(value:String):void {
            _passwordHash = value;
        }
        public function get passwordHash():String {
            return _passwordHash;
        }

        public function set roleAuthor(value:Boolean):void {
            _roleAuthor = value;
        }
        public function get roleAuthor():Boolean {
            return _roleAuthor;
        }

        public function set roleDeveloper(value:Boolean):void {
            _roleDeveloper = value;
        }
        public function get roleDeveloper():Boolean {
            return _roleDeveloper;
        }

        public function set roleTester(value:Boolean):void {
            _roleTester = value;
        }
        public function get roleTester():Boolean {
            return _roleTester;
        }

        public function set userName(value:String):void {
            _userName = value;
        }
        public function get userName():String {
            return _userName;
        }

        public function readExternal(input:IDataInput):void {
            _admin = input.readObject() as Boolean;
            _email = input.readObject() as String;
            _enabled = input.readObject() as Boolean;
            _firstName = input.readObject() as String;
            _id = input.readObject() as int;
            _locale = input.readObject() as String;
            _name = input.readObject() as String;
            _oe = input.readObject() as String;
            _passwordHash = input.readObject() as String;
            _roleAuthor = input.readObject() as Boolean;
            _roleDeveloper = input.readObject() as Boolean;
            _roleTester = input.readObject() as Boolean;
            _userName = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_admin);
            output.writeObject(_email);
            output.writeObject(_enabled);
            output.writeObject(_firstName);
            output.writeObject(_id);
            output.writeObject(_locale);
            output.writeObject(_name);
            output.writeObject(_oe);
            output.writeObject(_passwordHash);
            output.writeObject(_roleAuthor);
            output.writeObject(_roleDeveloper);
            output.writeObject(_roleTester);
            output.writeObject(_userName);
        }
    }
}