/**
 * Generated by Gas3 v1.0.1 (Granite Data Services) on Fri Mar 14 16:48:03 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Schritt.as).
 */

package ch.ess.tt.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ArrayCollection;

    [Bindable]
    public class SchrittBase implements IExternalizable {

        private var _fallList:ArrayCollection;
        private var _id:int;
        private var _nummer:int;
        private var _titel:String;

        public function set fallList(value:ArrayCollection):void {
            _fallList = value;
        }
        public function get fallList():ArrayCollection {
            return _fallList;
        }

        public function set id(value:int):void {
            _id = value;
        }
        public function get id():int {
            return _id;
        }

        public function set nummer(value:int):void {
            _nummer = value;
        }
        public function get nummer():int {
            return _nummer;
        }

        public function set titel(value:String):void {
            _titel = value;
        }
        public function get titel():String {
            return _titel;
        }

        public function readExternal(input:IDataInput):void {
            _fallList = input.readObject() as ArrayCollection;
            _id = input.readObject() as int;
            _nummer = input.readObject() as int;
            _titel = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_fallList);
            output.writeObject(_id);
            output.writeObject(_nummer);
            output.writeObject(_titel);
        }
    }
}