/**
 * Generated by Gas3 v1.0.1 (Granite Data Services) on Fri Mar 14 16:48:03 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Test.as).
 */

package ch.ess.tt.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ArrayCollection;

    [Bindable]
    public class TestBase implements IExternalizable {

        private var _beschreibung:String;
        private var _dateiContentSize1:int;
        private var _dateiContentSize2:int;
        private var _dateiContentSize3:int;
        private var _dateiFileName1:String;
        private var _dateiFileName2:String;
        private var _dateiFileName3:String;
        private var _datum:Date;
        private var _f1:int;
        private var _f1text:String;
        private var _f2:int;
        private var _f2text:String;
        private var _f3:int;
        private var _f3text:String;
        private var _f4:int;
        private var _f4text:String;
        private var _id:int;
        private var _informationen:String;
        private var _kurzbezeichnung:String;
        private var _name:String;
        private var _schrittList:ArrayCollection;
        private var _sprache:String;
        private var _status:String;
        private var _system:String;
        private var _versionTest:String;

        public function set beschreibung(value:String):void {
            _beschreibung = value;
        }
        public function get beschreibung():String {
            return _beschreibung;
        }

        public function set dateiContentSize1(value:int):void {
            _dateiContentSize1 = value;
        }
        public function get dateiContentSize1():int {
            return _dateiContentSize1;
        }

        public function set dateiContentSize2(value:int):void {
            _dateiContentSize2 = value;
        }
        public function get dateiContentSize2():int {
            return _dateiContentSize2;
        }

        public function set dateiContentSize3(value:int):void {
            _dateiContentSize3 = value;
        }
        public function get dateiContentSize3():int {
            return _dateiContentSize3;
        }

        public function set dateiFileName1(value:String):void {
            _dateiFileName1 = value;
        }
        public function get dateiFileName1():String {
            return _dateiFileName1;
        }

        public function set dateiFileName2(value:String):void {
            _dateiFileName2 = value;
        }
        public function get dateiFileName2():String {
            return _dateiFileName2;
        }

        public function set dateiFileName3(value:String):void {
            _dateiFileName3 = value;
        }
        public function get dateiFileName3():String {
            return _dateiFileName3;
        }

        public function set datum(value:Date):void {
            _datum = value;
        }
        public function get datum():Date {
            return _datum;
        }

        public function set f1(value:int):void {
            _f1 = value;
        }
        public function get f1():int {
            return _f1;
        }

        public function set f1text(value:String):void {
            _f1text = value;
        }
        public function get f1text():String {
            return _f1text;
        }

        public function set f2(value:int):void {
            _f2 = value;
        }
        public function get f2():int {
            return _f2;
        }

        public function set f2text(value:String):void {
            _f2text = value;
        }
        public function get f2text():String {
            return _f2text;
        }

        public function set f3(value:int):void {
            _f3 = value;
        }
        public function get f3():int {
            return _f3;
        }

        public function set f3text(value:String):void {
            _f3text = value;
        }
        public function get f3text():String {
            return _f3text;
        }

        public function set f4(value:int):void {
            _f4 = value;
        }
        public function get f4():int {
            return _f4;
        }

        public function set f4text(value:String):void {
            _f4text = value;
        }
        public function get f4text():String {
            return _f4text;
        }

        public function set id(value:int):void {
            _id = value;
        }
        public function get id():int {
            return _id;
        }

        public function set informationen(value:String):void {
            _informationen = value;
        }
        public function get informationen():String {
            return _informationen;
        }

        public function set kurzbezeichnung(value:String):void {
            _kurzbezeichnung = value;
        }
        public function get kurzbezeichnung():String {
            return _kurzbezeichnung;
        }

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function set schrittList(value:ArrayCollection):void {
            _schrittList = value;
        }
        public function get schrittList():ArrayCollection {
            return _schrittList;
        }

        public function set sprache(value:String):void {
            _sprache = value;
        }
        public function get sprache():String {
            return _sprache;
        }

        public function set status(value:String):void {
            _status = value;
        }
        public function get status():String {
            return _status;
        }

        public function set system(value:String):void {
            _system = value;
        }
        public function get system():String {
            return _system;
        }

        public function set versionTest(value:String):void {
            _versionTest = value;
        }
        public function get versionTest():String {
            return _versionTest;
        }

        public function readExternal(input:IDataInput):void {
            _beschreibung = input.readObject() as String;
            _dateiContentSize1 = input.readObject() as int;
            _dateiContentSize2 = input.readObject() as int;
            _dateiContentSize3 = input.readObject() as int;
            _dateiFileName1 = input.readObject() as String;
            _dateiFileName2 = input.readObject() as String;
            _dateiFileName3 = input.readObject() as String;
            _datum = input.readObject() as Date;
            _f1 = input.readObject() as int;
            _f1text = input.readObject() as String;
            _f2 = input.readObject() as int;
            _f2text = input.readObject() as String;
            _f3 = input.readObject() as int;
            _f3text = input.readObject() as String;
            _f4 = input.readObject() as int;
            _f4text = input.readObject() as String;
            _id = input.readObject() as int;
            _informationen = input.readObject() as String;
            _kurzbezeichnung = input.readObject() as String;
            _name = input.readObject() as String;
            _schrittList = input.readObject() as ArrayCollection;
            _sprache = input.readObject() as String;
            _status = input.readObject() as String;
            _system = input.readObject() as String;
            _versionTest = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_beschreibung);
            output.writeObject(_dateiContentSize1);
            output.writeObject(_dateiContentSize2);
            output.writeObject(_dateiContentSize3);
            output.writeObject(_dateiFileName1);
            output.writeObject(_dateiFileName2);
            output.writeObject(_dateiFileName3);
            output.writeObject(_datum);
            output.writeObject(_f1);
            output.writeObject(_f1text);
            output.writeObject(_f2);
            output.writeObject(_f2text);
            output.writeObject(_f3);
            output.writeObject(_f3text);
            output.writeObject(_f4);
            output.writeObject(_f4text);
            output.writeObject(_id);
            output.writeObject(_informationen);
            output.writeObject(_kurzbezeichnung);
            output.writeObject(_name);
            output.writeObject(_schrittList);
            output.writeObject(_sprache);
            output.writeObject(_status);
            output.writeObject(_system);
            output.writeObject(_versionTest);
        }
    }
}