package ch.rasc.wsdemo.helloworld;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated
 * source version: 2.2
 *
 */
@WebService(name = "HelloWorldImpl", targetNamespace = "http://wsdemo.rasc.ch/")
@XmlSeeAlso({ ObjectFactory.class })
public interface HelloWorldImpl {

	/**
	 *
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sayHi", targetNamespace = "http://wsdemo.rasc.ch/",
			className = "ch.rasc.wsdemo.helloworld.SayHi")
	@ResponseWrapper(localName = "sayHiResponse",
			targetNamespace = "http://wsdemo.rasc.ch/",
			className = "ch.rasc.wsdemo.helloworld.SayHiResponse")
	public String sayHi(@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
