package com.trivadis;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * Version 3.0.0
 *
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-30T12:30:52.420+01:00
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "LDAP_WS_v3_0", 
                  wsdlLocation = "file:/D:/ws/geverdummy/src/main/wsdl/LDAP_WS_v3_0.wsdl",
                  targetNamespace = "http://www.trivadis.com/") 
public class LDAPWSV30 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.trivadis.com/", "LDAP_WS_v3_0");
    public final static QName LDAPWSV30Soap = new QName("http://www.trivadis.com/", "LDAP_WS_v3_0Soap");
    public final static QName LDAPWSV30Soap12 = new QName("http://www.trivadis.com/", "LDAP_WS_v3_0Soap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/ws/geverdummy/src/main/wsdl/LDAP_WS_v3_0.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LDAPWSV30.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/ws/geverdummy/src/main/wsdl/LDAP_WS_v3_0.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LDAPWSV30(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LDAPWSV30(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LDAPWSV30() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns LDAPWSV30Soap
     */
    @WebEndpoint(name = "LDAP_WS_v3_0Soap")
    public LDAPWSV30Soap getLDAPWSV30Soap() {
        return super.getPort(LDAPWSV30Soap, LDAPWSV30Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LDAPWSV30Soap
     */
    @WebEndpoint(name = "LDAP_WS_v3_0Soap")
    public LDAPWSV30Soap getLDAPWSV30Soap(WebServiceFeature... features) {
        return super.getPort(LDAPWSV30Soap, LDAPWSV30Soap.class, features);
    }
    /**
     *
     * @return
     *     returns LDAPWSV30Soap
     */
    @WebEndpoint(name = "LDAP_WS_v3_0Soap12")
    public LDAPWSV30Soap getLDAPWSV30Soap12() {
        return super.getPort(LDAPWSV30Soap12, LDAPWSV30Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LDAPWSV30Soap
     */
    @WebEndpoint(name = "LDAP_WS_v3_0Soap12")
    public LDAPWSV30Soap getLDAPWSV30Soap12(WebServiceFeature... features) {
        return super.getPort(LDAPWSV30Soap12, LDAPWSV30Soap.class, features);
    }

}
