logging:
  level:
    org.springframework.web.servlet: INFO
spring:
  mvc:
      async:
        request-timeout: 1000000
mongodb:
  uri: mongodb://localhost/messenger?w=1&wtimeoutMS=0&journal=true     
        