/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Fri Aug 15 14:37:22 CEST 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package ch.ess.startstop.entity {

    [Bindable]
    [RemoteClass(alias="ch.ess.startstop.entity.Info")]
    public class Info extends InfoBase {
    }
}