app.relying-party-id=localhost
app.relying-party-name=Example Application
app.relying-party-origins=http://localhost:8100

# Optional CORS origins (comma separated). If not set, `app.relying-party-origins` is used.
app.cors-origins=http://localhost:8100
