/*
 * This file is generated by jOOQ.
 */
package ch.rasc.sqrldemo.db;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import ch.rasc.sqrldemo.db.tables.AppUser;
import ch.rasc.sqrldemo.db.tables.PreviousIdentityKey;

/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.12.3" },
		comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

	// -------------------------------------------------------------------------
	// INDEX definitions
	// -------------------------------------------------------------------------

	public static final Index CONSTRAINT_INDEX_7 = Indexes0.CONSTRAINT_INDEX_7;
	public static final Index PRIMARY_KEY_7 = Indexes0.PRIMARY_KEY_7;
	public static final Index CONSTRAINT_INDEX_4 = Indexes0.CONSTRAINT_INDEX_4;
	public static final Index PRIMARY_KEY_4 = Indexes0.PRIMARY_KEY_4;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Indexes0 {
		public static Index CONSTRAINT_INDEX_7 = Internal.createIndex(
				"CONSTRAINT_INDEX_7", AppUser.APP_USER,
				new OrderField[] { AppUser.APP_USER.IDENTITY_KEY }, true);
		public static Index PRIMARY_KEY_7 = Internal.createIndex("PRIMARY_KEY_7",
				AppUser.APP_USER, new OrderField[] { AppUser.APP_USER.ID }, true);
		public static Index CONSTRAINT_INDEX_4 = Internal
				.createIndex("CONSTRAINT_INDEX_4",
						PreviousIdentityKey.PREVIOUS_IDENTITY_KEY,
						new OrderField[] {
								PreviousIdentityKey.PREVIOUS_IDENTITY_KEY.APP_USER_ID },
						false);
		public static Index PRIMARY_KEY_4 = Internal.createIndex("PRIMARY_KEY_4",
				PreviousIdentityKey.PREVIOUS_IDENTITY_KEY,
				new OrderField[] { PreviousIdentityKey.PREVIOUS_IDENTITY_KEY.APP_USER_ID,
						PreviousIdentityKey.PREVIOUS_IDENTITY_KEY.PREV_IDENTITY_KEY },
				true);
	}
}
