/*
 * This file is generated by jOOQ.
 */
package ch.rasc.sqrldemo.db;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import ch.rasc.sqrldemo.db.tables.AppUser;
import ch.rasc.sqrldemo.db.tables.PreviousIdentityKey;
import ch.rasc.sqrldemo.db.tables.records.AppUserRecord;
import ch.rasc.sqrldemo.db.tables.records.PreviousIdentityKeyRecord;

/**
 * A class modelling foreign key relationships and constraints of tables of the
 * <code></code> schema.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.12.3" },
		comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<AppUserRecord, Long> IDENTITY_APP_USER = Identities0.IDENTITY_APP_USER;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<AppUserRecord> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;
	public static final UniqueKey<AppUserRecord> CONSTRAINT_76 = UniqueKeys0.CONSTRAINT_76;
	public static final UniqueKey<PreviousIdentityKeyRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<PreviousIdentityKeyRecord, AppUserRecord> CONSTRAINT_4C = ForeignKeys0.CONSTRAINT_4C;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 {
		public static Identity<AppUserRecord, Long> IDENTITY_APP_USER = Internal
				.createIdentity(AppUser.APP_USER, AppUser.APP_USER.ID);
	}

	private static class UniqueKeys0 {
		public static final UniqueKey<AppUserRecord> CONSTRAINT_7 = Internal
				.createUniqueKey(AppUser.APP_USER, "CONSTRAINT_7", AppUser.APP_USER.ID);
		public static final UniqueKey<AppUserRecord> CONSTRAINT_76 = Internal
				.createUniqueKey(AppUser.APP_USER, "CONSTRAINT_76",
						AppUser.APP_USER.IDENTITY_KEY);
		public static final UniqueKey<PreviousIdentityKeyRecord> CONSTRAINT_4 = Internal
				.createUniqueKey(PreviousIdentityKey.PREVIOUS_IDENTITY_KEY,
						"CONSTRAINT_4",
						PreviousIdentityKey.PREVIOUS_IDENTITY_KEY.APP_USER_ID,
						PreviousIdentityKey.PREVIOUS_IDENTITY_KEY.PREV_IDENTITY_KEY);
	}

	private static class ForeignKeys0 {
		public static final ForeignKey<PreviousIdentityKeyRecord, AppUserRecord> CONSTRAINT_4C = Internal
				.createForeignKey(ch.rasc.sqrldemo.db.Keys.CONSTRAINT_7,
						PreviousIdentityKey.PREVIOUS_IDENTITY_KEY, "CONSTRAINT_4C",
						PreviousIdentityKey.PREVIOUS_IDENTITY_KEY.APP_USER_ID);
	}
}
