/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Fri Jun 13 15:35:41 CEST 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.jboss.seam.example.booking {

    [Bindable]
    [RemoteClass(alias="org.jboss.seam.example.booking.Booking")]
    public class Booking extends BookingBase {

        public function get total():Number {
            return this.hotel.price * nights;
        }

        public function get nights():Number {
             return Number(( checkoutDate.getTime() - checkinDate.getTime()) / 1000 / 60 / 60 / 24);
        }
    }
}