/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Fri Jun 13 15:35:40 CEST 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.jboss.seam.example.booking {

    [Bindable]
    [RemoteClass(alias="org.jboss.seam.example.booking.Hotel")]
    public class Hotel extends HotelBase {

        public function get CityState():String {
            return city + ", " + state;
        }
    }
}