INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Crane','Magee','Cairns','Halifax');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Dawson','Upton','Norderstedt','Trento');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Stanley','Acton','Castanhal','Hospet');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Cantrell','Dominique','Fallais','San Polo d''Enza');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Talley','Tanner','Moerkerke','Cagliari');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('West','Aurora','Bressoux','Pavone del Mella');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Mcclain','Denton','Destelbergen','Castelbuono');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Irwin','Denise','Castelnuovo Magra','Penrith');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Glass','Halla','Kelkheim','Arbroath');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Fuentes','Winter','Zandhoven','Dunkerque');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Whitaker','Tamara','Sainte-Marie-sur-Semois','Dreux');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Santiago','Jared','Koersel','Lissewege');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Poole','Kessie','Coldstream','Las Vegas');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Heath','Roary','Tresigallo','Kleinmachnow');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Conley','Alana','St. Catharines','Bally');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Cash','Jesse','Kerkrade','Wichelen');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Chavez','Tatiana','Klosterneuburg','Fossato Serralta');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Morgan','Gil','Junagadh','Seraing');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Stein','Wyoming','Mosciano Sant''Angelo','Town of Yarmouth');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Lott','Caldwell','Bognor Regis','Upper Hutt');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Vance','Dustin','Ellesmere Port','Newtown');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Livingston','Adena','Bhusawal','Huppaye');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Bernard','Caleb','Lairg','La Roche-sur-Yon');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Bolton','Dorothy','Marlborough','Orciano Pisano');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Horne','Chadwick','Le Petit-Quevilly','Blairgowrie');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Pearson','Lars','Fosses-la-Ville','Bankura');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Dixon','Lael','Monacilioni','Roosdaal');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('May','Kimberley','Bossire','Corbais');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Jacobson','Lisandra','Caprino Bergamasco','Stoke-on-Trent');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Hicks','Ivana','Warminster','Patan');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Kennedy','Brynne','Lille','Grand Falls');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Cobb','Hiram','Folx-les-Caves','Leganés');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Sosa','Joseph','Vegreville','São Gonçalo');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Moss','Shellie','Kapuskasing','Hasselt');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Combs','Zephr','Maranello','Annapolis Royal');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Matthews','Hiram','Pangnirtung','Doetinchem');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Wheeler','Hu','Chiaromonte','Worcester');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Petersen','Micah','Hudson''s Hope','Helensburgh');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Britt','Shad','Drayton Valley','Namen');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Guerra','Adele','Township of Minden Hills','Gulbarga');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Lawrence','Wyatt','Arnhem','Erode');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('English','Mufutau','Monghidoro','Greymouth');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Haynes','Inez','Moose Jaw','Orangeville');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Goodwin','Harlan','Dubuisson','Oud-Turnhout');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Robertson','Aiko','Carpignano Salentino','Zamora');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Benjamin','Nero','Stornaway','Houdemont');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Moran','April','Calco','St. John''s');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Barr','Pascale','Westkerke','Bearberry');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Kirk','Dorothy','Henstedt-Ulzburg','Ham-sur-Heure-Nalinnes');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Oconnor','Hamish','Camaçari','Lens');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Malone','Valentine','Mumbai','Lansing');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Stuart','Rahim','Emden','Siegendorf');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Hogan','Beatrice','Jhelum','Attigliano');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Reese','Hayes','Launceston','Sautin');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Solis','Benedict','Kermt','Lozzo Atestino');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Kent','Mariam','Bitterfeld-Wolfen','La Thuile');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Sandoval','Nichole','Bathurst','Nivelles');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Hicks','Emi','Yeovil','Green Bay');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Wiley','Ainsley','Tiruvottiyur','Rochester');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Hatfield','Diana','Flawinne','Francofonte');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Maynard','Ginger','Medea','Quèbec City');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Moss','Raja','Nieuwenrode','Habergy');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Mays','Nicholas','Beervelde','Málaga');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Chang','Uriel','Sant''Agata sul Santerno','Glabais');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Phillips','Regina','Betim','Gignod');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Curtis','Caesar','Heredia','Asbestos');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Holmes','Rylee','Toledo','San Pietro Avellana');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Coleman','Moana','Tavigny','Broken Arrow');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Moss','Winifred','Vandoeuvre-lès-Nancy','Ougre');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Whitaker','Bo','Canmore','Kettering');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Barron','Rudyard','Vienna','Kortessem');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Vance','Caesar','Geer','Greifswald');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Floyd','Kasimir','Mount Isa','Santa Caterina Villarmosa');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Mays','Abbot','Chetwynd','Neuwied');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Holder','Aspen','Diano Arentino','Hunstanton');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Simmons','Gage','Anzi','Guirsch');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Franco','Yen','Sant''Angelo a Cupolo','Annapolis');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Rojas','Hop','Bhopal','Timkur');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Dudley','Bert','Fumal','Berg');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Petty','Karly','Davoli','Dewas');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Stephens','Stone','Ferlach','Saint Paul');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Harrison','Solomon','Sandy','Penicuik');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Branch','Dorian','LaSalle','Hamilton');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Simpson','Nathaniel','Newbury','Burg');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Abbott','Ishmael','Onoz','Kelowna');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Schroeder','Shoshana','Dreux','Ingraj Bazar');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Hyde','Andrew','Bhilai','Sudbury');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Moody','Chaim','Villa Cortese','Niort');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Holden','Shannon','Rechnitz','Nieuwegein');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Harvey','Aquila','Griesheim','Naihati');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Mcfadden','Odette','Blevio','Lauco');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Sullivan','Lucian','West Jordan','Herne');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Rosa','Tara','Kota','Saint-Brieuc');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Ballard','Erich','Masullas','Côte-Saint-Luc');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Baldwin','Macy','La Seyne-sur-Mer','Herstappe');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Blevins','Bertha','Lasne','Vannes');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Crawford','Lee','Ramsdonk','Peterhead');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Acosta','Lois','Vauda Canavese','Grey County');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Ashley','Rina','Canterano','Matagami');
INSERT INTO `address` (`firstName`,`lastName`,`street`,`city`) VALUES ('Hernandez','Randall','Nijlen','Norderstedt');