/**
 * Generated by Gas3 v1.0.0 (Granite Data Services) on Mon Jan 21 12:46:49 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (HomepageNewsText.as).
 */

package ch.ess.hpadmin.entity {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class HomepageNewsTextBase implements IExternalizable {

        private var __laziness:String = null;

        private var _homepageLanguage:HomepageLanguage;
        private var _homepageNews:HomepageNews;
        private var _id:HomepageNewsTextId;
        private var _text:String;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is HomepageNewsText) || (property as HomepageNewsText).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set homepageLanguage(value:HomepageLanguage):void {
            _homepageLanguage = value;
        }
        public function get homepageLanguage():HomepageLanguage {
            return _homepageLanguage;
        }

        public function set homepageNews(value:HomepageNews):void {
            _homepageNews = value;
        }
        public function get homepageNews():HomepageNews {
            return _homepageNews;
        }

        public function set id(value:HomepageNewsTextId):void {
            _id = value;
        }
        public function get id():HomepageNewsTextId {
            return _id;
        }

        public function set text(value:String):void {
            _text = value;
        }
        public function get text():String {
            return _text;
        }

        public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                _homepageLanguage = input.readObject() as HomepageLanguage;
                _homepageNews = input.readObject() as HomepageNews;
                _id = input.readObject() as HomepageNewsTextId;
                _text = input.readObject() as String;
            }
            else {
                _id = input.readObject() as HomepageNewsTextId;
            }
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                output.writeObject(_homepageLanguage);
                output.writeObject(_homepageNews);
                output.writeObject(_id);
                output.writeObject(_text);
            }
            else {
                output.writeObject(_id);
            }
        }
    }
}