/**
 * Generated by Gas3 v1.0.0 (Granite Data Services) on Sun Jan 20 14:47:33 CET 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package ch.ess.hpadmin.entity {

    [Bindable]
    [RemoteClass(alias="ch.ess.hpadmin.entity.HomepageFieldTextresId")]
    public class HomepageFieldTextresId extends HomepageFieldTextresIdBase {
    }
}