/**
 * Generated by Gas3 v1.0.0 (Granite Data Services) on Mon Jan 21 12:46:49 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (HomepagePage.as).
 */

package ch.ess.hpadmin.entity {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ArrayCollection;
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class HomepagePageBase implements IExternalizable {

        private var __laziness:String = null;

        private var _homepagePage:HomepagePage;
        private var _homepagePages:ArrayCollection;
        private var _homepageTemplate:HomepageTemplate;
        private var _id:Number;
        private var _name:String;
        private var _priority:Number;
        private var _title:String;
        private var _visibility:Number;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is HomepagePage) || (property as HomepagePage).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set homepagePage(value:HomepagePage):void {
            _homepagePage = value;
        }
        public function get homepagePage():HomepagePage {
            return _homepagePage;
        }

        public function set homepagePages(value:ArrayCollection):void {
            _homepagePages = value;
        }
        public function get homepagePages():ArrayCollection {
            return _homepagePages;
        }

        public function set homepageTemplate(value:HomepageTemplate):void {
            _homepageTemplate = value;
        }
        public function get homepageTemplate():HomepageTemplate {
            return _homepageTemplate;
        }

        public function set id(value:Number):void {
            _id = value;
        }
        public function get id():Number {
            return _id;
        }

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function set priority(value:Number):void {
            _priority = value;
        }
        public function get priority():Number {
            return _priority;
        }

        public function set title(value:String):void {
            _title = value;
        }
        public function get title():String {
            return _title;
        }

        public function set visibility(value:Number):void {
            _visibility = value;
        }
        public function get visibility():Number {
            return _visibility;
        }

        public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                _homepagePage = input.readObject() as HomepagePage;
                _homepagePages = input.readObject() as ArrayCollection;
                _homepageTemplate = input.readObject() as HomepageTemplate;
                _id = input.readObject() as Number;
                _name = input.readObject() as String;
                _priority = input.readObject() as Number;
                _title = input.readObject() as String;
                _visibility = input.readObject() as Number;
            }
            else {
                _id = input.readObject() as Number;
            }
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                output.writeObject(_homepagePage);
                output.writeObject(_homepagePages);
                output.writeObject(_homepageTemplate);
                output.writeObject(_id);
                output.writeObject(_name);
                output.writeObject(_priority);
                output.writeObject(_title);
                output.writeObject(_visibility);
            }
            else {
                output.writeObject(_id);
            }
        }
    }
}