/**
 * Generated by Gas3 v1.0.0 (Granite Data Services) on Mon Jan 21 12:46:49 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (HomepageFieldTextresId.as).
 */

package ch.ess.hpadmin.entity {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class HomepageFieldTextresIdBase implements IExternalizable {

        private var _fieldId:Number;
        private var _langId:Number;

        public function set fieldId(value:Number):void {
            _fieldId = value;
        }
        public function get fieldId():Number {
            return _fieldId;
        }

        public function set langId(value:Number):void {
            _langId = value;
        }
        public function get langId():Number {
            return _langId;
        }

        public function readExternal(input:IDataInput):void {
            _fieldId = input.readObject() as Number;
            _langId = input.readObject() as Number;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_fieldId);
            output.writeObject(_langId);
        }
    }
}