/**
 * Generated by Gas3 v1.0.0 (Granite Data Services) on Mon Jan 21 12:46:49 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (HomepageTextResource.as).
 */

package ch.ess.hpadmin.entity {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ArrayCollection;
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class HomepageTextResourceBase implements IExternalizable {

        private var __laziness:String = null;

        private var _homepageFieldTextreses:ArrayCollection;
        private var _id:Number;
        private var _text:String;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is HomepageTextResource) || (property as HomepageTextResource).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set homepageFieldTextreses(value:ArrayCollection):void {
            _homepageFieldTextreses = value;
        }
        public function get homepageFieldTextreses():ArrayCollection {
            return _homepageFieldTextreses;
        }

        public function set id(value:Number):void {
            _id = value;
        }
        public function get id():Number {
            return _id;
        }

        public function set text(value:String):void {
            _text = value;
        }
        public function get text():String {
            return _text;
        }

        public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                _homepageFieldTextreses = input.readObject() as ArrayCollection;
                _id = input.readObject() as Number;
                _text = input.readObject() as String;
            }
            else {
                _id = input.readObject() as Number;
            }
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                output.writeObject(_homepageFieldTextreses);
                output.writeObject(_id);
                output.writeObject(_text);
            }
            else {
                output.writeObject(_id);
            }
        }
    }
}