/**
 * Generated by Gas3 v1.0.0 (Granite Data Services) on Mon Jan 21 12:46:49 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (HomepageLanguage.as).
 */

package ch.ess.hpadmin.entity {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ArrayCollection;
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class HomepageLanguageBase implements IExternalizable {

        private var __laziness:String = null;

        private var _active:Number;
        private var _homepageFieldTextreses:ArrayCollection;
        private var _homepageNewsTexts:ArrayCollection;
        private var _id:Number;
        private var _iso:String;
        private var _name:String;
        private var _priority:Number;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is HomepageLanguage) || (property as HomepageLanguage).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set active(value:Number):void {
            _active = value;
        }
        public function get active():Number {
            return _active;
        }

        public function set homepageFieldTextreses(value:ArrayCollection):void {
            _homepageFieldTextreses = value;
        }
        public function get homepageFieldTextreses():ArrayCollection {
            return _homepageFieldTextreses;
        }

        public function set homepageNewsTexts(value:ArrayCollection):void {
            _homepageNewsTexts = value;
        }
        public function get homepageNewsTexts():ArrayCollection {
            return _homepageNewsTexts;
        }

        public function set id(value:Number):void {
            _id = value;
        }
        public function get id():Number {
            return _id;
        }

        public function set iso(value:String):void {
            _iso = value;
        }
        public function get iso():String {
            return _iso;
        }

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function set priority(value:Number):void {
            _priority = value;
        }
        public function get priority():Number {
            return _priority;
        }

        public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                _active = input.readObject() as Number;
                _homepageFieldTextreses = input.readObject() as ArrayCollection;
                _homepageNewsTexts = input.readObject() as ArrayCollection;
                _id = input.readObject() as Number;
                _iso = input.readObject() as String;
                _name = input.readObject() as String;
                _priority = input.readObject() as Number;
            }
            else {
                _id = input.readObject() as Number;
            }
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                output.writeObject(_active);
                output.writeObject(_homepageFieldTextreses);
                output.writeObject(_homepageNewsTexts);
                output.writeObject(_id);
                output.writeObject(_iso);
                output.writeObject(_name);
                output.writeObject(_priority);
            }
            else {
                output.writeObject(_id);
            }
        }
    }
}