Ext.define('Changelog.model.Customer', {
	extend: 'Ext.data.Model',
	fields: [ {
		name: 'id',
		type: 'int'
	}, {
		name: 'shortName',
		type: 'string'
	}, {
		name: 'longName',
		type: 'string'
	}, {
		name: 'testUrl',
		type: 'string'
	}, {
		name: 'ftpUser',
		type: 'string'
	}, {
		name: 'responsible',
		type: 'string'			
	}, {
		name: 'integration',
		type: 'string'			
	}, {
		name: 'schnittstellen',
		type: 'string'			
	}, {
		name: 'standalone',
		type: 'string'			
	}, {
		name: 'db',
		type: 'string'			
	}, {
		name: 'tomcat',
		type: 'string'			
	}, {
		name: 'java',
		type: 'string'			
	}, {
		name: 'os',
		type: 'string'			
	}, {
		name: 'iis',
		type: 'string'			
	}, {
		name: 'browser',
		type: 'string'			
	}, {
		name: 'url',
		type: 'string'			
	}, {
		name: 'vpn',
		type: 'string'			
	}, {
		name: 'noVertraege',
		type: 'string'			
	}, {
		name: 'bemerkungen',
		type: 'string'			
	}, {
		name: 'ansprechperson',
		type: 'string'			
	}, {
		name: 'applikationsmgmt',
		type: 'string'			
	}, {
		name: 'latestVersionNumber',
		type: 'string',
		persist: false
	}, {
		name: 'latestVersionDate',
		type: 'date',
		dateFormat: 'd.m.Y',
		persist: false
	}, {
		name: 'installation',
		type: 'string'
	}, {
		name: 'alogin',
		type: 'string'
	}, {
		name: 'langdeCH',
		type: 'string'
	}, {
		name: 'langfr',
		type: 'string'
	}, {
		name: 'langen',
		type: 'string'
	}, {
		name: 'ct',
		type: 'string'
	}, {
		name: 'lis',
		type: 'string'
	}, {
		name: 'lms',
		type: 'string'
	}, {
		name: 'lic',
		type: 'string'
	}, {
		name: 'clm',
		type: 'string'
	}, {
		name: 'inv',
		type: 'string'
	}, {
		name: 'par',
		type: 'string'
	}, {
		name: 'vertragAutoNr',
		type: 'string'
	}, {
		name: 'gen',
		type: 'string'
	}],

	proxy: {
		type: 'direct',
		api: {
			read: 'customerService.load',
			create: 'customerService.create',
			update: 'customerService.update',
			destroy: 'customerService.destroy'
		},
		reader: {
			root: 'records'
		}
	}
});