//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DVE.RC
//
#define IDR_MAIN_ICON                   2
#define IDR_MAIN_ACCEL                  3
#define IDD_ABOUTBOX                    100
#define MAIN_DLG_WINDOW                 101
#define IDR_MAIN_MENU                   102
#define IDD_DIALOG1                     104
#define IDD_SPIELSTAND                  104
#define IDD_STRATEGIE                   105
#define IDD_ZIELDIALOG                  106
#define IDC_WUERFELN                    1001
#define IDC_RUNDEBEENDEN                1002
#define IDC_WURF                        1007
#define IDC_RPTECOMP                    1008
#define IDC_TOTALCOMP                   1009
#define IDC_RPTEHUMA                    1010
#define IDC_TOTALHUMA                   1011
#define IDC_ZIEL                        1012
#define IDC_SSHUMA                      1013
#define IDC_SSCOMP                      1014
#define S                               1015
#define IDC_ZIELPUNKTE                  1040
#define IDC_SCROLLZIEL                  1041
#define ID_ABOUT                        32771
#define ID_DIALOGS_FILEOPEN             32773
#define ID_DIALOGS_FILESAVE             32774
#define ID_DIALOGS_FONT                 32775
#define ID_DIALOGS_COLOR                32776
#define ID_DIALOGS_PRINT                32777
#define ID_DIALOGS_ABOUT                32778
#define ID_SPIELSTAND                   32779
#define ID_STRATEGIE                    32780
#define ID_MELDUNG                      32781
#define ID_ZIEL                         32782
#define ID_FRAME1                       -1
#define ID_FRAME2                       -1
#define ID_FRAME3                       -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
