/**
 * Generated by Gas3 v1.0.0 (Granite Data Services) on Mon Jan 21 05:58:50 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (JahrItem.as).
 */

package ch.ess.hgtracker.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class JahrItemBase implements IExternalizable {

        private var _jahr:int;
        private var _label:String;

        public function set jahr(value:int):void {
            _jahr = value;
        }
        public function get jahr():int {
            return _jahr;
        }

        public function set label(value:String):void {
            _label = value;
        }
        public function get label():String {
            return _label;
        }

        public function readExternal(input:IDataInput):void {
            _jahr = input.readObject() as int;
            _label = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_jahr);
            output.writeObject(_label);
        }
    }
}