/**
 * Generated by Gas3 v1.0.0 (Granite Data Services) on Mon Jan 21 06:09:17 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (PunkteAnzeige.as).
 */

package ch.ess.hgtracker.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class PunkteAnzeigeBase implements IExternalizable {

        private var _id:int;
        private var _jahrgang:Number;
        private var _nachname:String;
        private var _nr1:Boolean;
        private var _nr2:Boolean;
        private var _nr3:Boolean;
        private var _nr4:Boolean;
        private var _nr5:Boolean;
        private var _nr6:Boolean;
        private var _rangpunkte:Number;
        private var _reihenfolge:Number;
        private var _ries1:String;
        private var _ries2:String;
        private var _ries3:String;
        private var _ries4:String;
        private var _ries5:String;
        private var _ries6:String;
        private var _total:int;
        private var _vorname:String;

        public function set id(value:int):void {
            _id = value;
        }
        public function get id():int {
            return _id;
        }

        public function set jahrgang(value:Number):void {
            _jahrgang = value;
        }
        public function get jahrgang():Number {
            return _jahrgang;
        }

        public function set nachname(value:String):void {
            _nachname = value;
        }
        public function get nachname():String {
            return _nachname;
        }

        public function set nr1(value:Boolean):void {
            _nr1 = value;
        }
        public function get nr1():Boolean {
            return _nr1;
        }

        public function set nr2(value:Boolean):void {
            _nr2 = value;
        }
        public function get nr2():Boolean {
            return _nr2;
        }

        public function set nr3(value:Boolean):void {
            _nr3 = value;
        }
        public function get nr3():Boolean {
            return _nr3;
        }

        public function set nr4(value:Boolean):void {
            _nr4 = value;
        }
        public function get nr4():Boolean {
            return _nr4;
        }

        public function set nr5(value:Boolean):void {
            _nr5 = value;
        }
        public function get nr5():Boolean {
            return _nr5;
        }

        public function set nr6(value:Boolean):void {
            _nr6 = value;
        }
        public function get nr6():Boolean {
            return _nr6;
        }

        public function set rangpunkte(value:Number):void {
            _rangpunkte = value;
        }
        public function get rangpunkte():Number {
            return _rangpunkte;
        }

        public function set reihenfolge(value:Number):void {
            _reihenfolge = value;
        }
        public function get reihenfolge():Number {
            return _reihenfolge;
        }

        public function set ries1(value:String):void {
            _ries1 = value;
        }
        public function get ries1():String {
            return _ries1;
        }

        public function set ries2(value:String):void {
            _ries2 = value;
        }
        public function get ries2():String {
            return _ries2;
        }

        public function set ries3(value:String):void {
            _ries3 = value;
        }
        public function get ries3():String {
            return _ries3;
        }

        public function set ries4(value:String):void {
            _ries4 = value;
        }
        public function get ries4():String {
            return _ries4;
        }

        public function set ries5(value:String):void {
            _ries5 = value;
        }
        public function get ries5():String {
            return _ries5;
        }

        public function set ries6(value:String):void {
            _ries6 = value;
        }
        public function get ries6():String {
            return _ries6;
        }

        public function set total(value:int):void {
            _total = value;
        }
        public function get total():int {
            return _total;
        }

        public function set vorname(value:String):void {
            _vorname = value;
        }
        public function get vorname():String {
            return _vorname;
        }

        public function readExternal(input:IDataInput):void {
            _id = input.readObject() as int;
            _jahrgang = input.readObject() as Number;
            _nachname = input.readObject() as String;
            _nr1 = input.readObject() as Boolean;
            _nr2 = input.readObject() as Boolean;
            _nr3 = input.readObject() as Boolean;
            _nr4 = input.readObject() as Boolean;
            _nr5 = input.readObject() as Boolean;
            _nr6 = input.readObject() as Boolean;
            _rangpunkte = input.readObject() as Number;
            _reihenfolge = input.readObject() as Number;
            _ries1 = input.readObject() as String;
            _ries2 = input.readObject() as String;
            _ries3 = input.readObject() as String;
            _ries4 = input.readObject() as String;
            _ries5 = input.readObject() as String;
            _ries6 = input.readObject() as String;
            _total = input.readObject() as int;
            _vorname = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_id);
            output.writeObject(_jahrgang);
            output.writeObject(_nachname);
            output.writeObject(_nr1);
            output.writeObject(_nr2);
            output.writeObject(_nr3);
            output.writeObject(_nr4);
            output.writeObject(_nr5);
            output.writeObject(_nr6);
            output.writeObject(_rangpunkte);
            output.writeObject(_reihenfolge);
            output.writeObject(_ries1);
            output.writeObject(_ries2);
            output.writeObject(_ries3);
            output.writeObject(_ries4);
            output.writeObject(_ries5);
            output.writeObject(_ries6);
            output.writeObject(_total);
            output.writeObject(_vorname);
        }
    }
}