/**
 * Generated by Gas3 v1.0.0 (Granite Data Services) on Mon Jan 21 05:58:50 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Rangpunkte.as).
 */

package ch.ess.hgtracker.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class RangpunkteBase implements IExternalizable {

        private var _chartLabel:String;
        private var _jahrgang:Number;
        private var _nachname:String;
        private var _punkte:Number;
        private var _punkteProSpiel:Number;
        private var _rangpunkte:Number;
        private var _schnitt:Number;
        private var _striche:Number;
        private var _vorname:String;

        public function set chartLabel(value:String):void {
            _chartLabel = value;
        }
        public function get chartLabel():String {
            return _chartLabel;
        }

        public function set jahrgang(value:Number):void {
            _jahrgang = value;
        }
        public function get jahrgang():Number {
            return _jahrgang;
        }

        public function set nachname(value:String):void {
            _nachname = value;
        }
        public function get nachname():String {
            return _nachname;
        }

        public function set punkte(value:Number):void {
            _punkte = value;
        }
        public function get punkte():Number {
            return _punkte;
        }

        public function set punkteProSpiel(value:Number):void {
            _punkteProSpiel = value;
        }
        public function get punkteProSpiel():Number {
            return _punkteProSpiel;
        }

        public function set rangpunkte(value:Number):void {
            _rangpunkte = value;
        }
        public function get rangpunkte():Number {
            return _rangpunkte;
        }

        public function set schnitt(value:Number):void {
            _schnitt = value;
        }
        public function get schnitt():Number {
            return _schnitt;
        }

        public function set striche(value:Number):void {
            _striche = value;
        }
        public function get striche():Number {
            return _striche;
        }

        public function set vorname(value:String):void {
            _vorname = value;
        }
        public function get vorname():String {
            return _vorname;
        }

        public function readExternal(input:IDataInput):void {
            _chartLabel = input.readObject() as String;
            _jahrgang = input.readObject() as Number;
            _nachname = input.readObject() as String;
            _punkte = input.readObject() as Number;
            _punkteProSpiel = input.readObject() as Number;
            _rangpunkte = input.readObject() as Number;
            _schnitt = input.readObject() as Number;
            _striche = input.readObject() as Number;
            _vorname = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_chartLabel);
            output.writeObject(_jahrgang);
            output.writeObject(_nachname);
            output.writeObject(_punkte);
            output.writeObject(_punkteProSpiel);
            output.writeObject(_rangpunkte);
            output.writeObject(_schnitt);
            output.writeObject(_striche);
            output.writeObject(_vorname);
        }
    }
}