/**
 * Generated by Gas3 v1.0.0 (Granite Data Services) on Tue Jan 15 23:55:12 CET 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package ch.ess.hgtracker.model {

    [Bindable]
    [RemoteClass(alias="ch.ess.hgtracker.model.SpielAnzeige")]
    public class SpielAnzeige extends SpielAnzeigeBase {
    }
}