/**
 * Generated by Gas3 v1.0.0 (Granite Data Services) on Mon Jan 21 05:58:50 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (SpielForm.as).
 */

package ch.ess.hgtracker.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class SpielFormBase implements IExternalizable {

        private var _datum:String;
        private var _gegner:String;
        private var _id:int;
        private var _kampfrichter:String;
        private var _kampfrichterGegner:String;
        private var _minuten:String;
        private var _name:String;
        private var _ort:String;
        private var _punkteId:int;
        private var _ries1nr:Boolean;
        private var _ries2nr:Boolean;
        private var _ries3nr:Boolean;
        private var _ries4nr:Boolean;
        private var _ries5nr:Boolean;
        private var _ries6nr:Boolean;
        private var _schlagPunkteGegner:String;
        private var _showries1nr:Boolean;
        private var _showries2nr:Boolean;
        private var _showries3nr:Boolean;
        private var _showries4nr:Boolean;
        private var _showries5nr:Boolean;
        private var _showries6nr:Boolean;
        private var _spielArt:String;
        private var _stunden:String;
        private var _totalNr:String;
        private var _totalNrAlt:int;
        private var _totalNrHeim:String;

        public function set datum(value:String):void {
            _datum = value;
        }
        public function get datum():String {
            return _datum;
        }

        public function set gegner(value:String):void {
            _gegner = value;
        }
        public function get gegner():String {
            return _gegner;
        }

        public function set id(value:int):void {
            _id = value;
        }
        public function get id():int {
            return _id;
        }

        public function set kampfrichter(value:String):void {
            _kampfrichter = value;
        }
        public function get kampfrichter():String {
            return _kampfrichter;
        }

        public function set kampfrichterGegner(value:String):void {
            _kampfrichterGegner = value;
        }
        public function get kampfrichterGegner():String {
            return _kampfrichterGegner;
        }

        public function set minuten(value:String):void {
            _minuten = value;
        }
        public function get minuten():String {
            return _minuten;
        }

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function set ort(value:String):void {
            _ort = value;
        }
        public function get ort():String {
            return _ort;
        }

        public function set punkteId(value:int):void {
            _punkteId = value;
        }
        public function get punkteId():int {
            return _punkteId;
        }

        public function set ries1nr(value:Boolean):void {
            _ries1nr = value;
        }
        public function get ries1nr():Boolean {
            return _ries1nr;
        }

        public function set ries2nr(value:Boolean):void {
            _ries2nr = value;
        }
        public function get ries2nr():Boolean {
            return _ries2nr;
        }

        public function set ries3nr(value:Boolean):void {
            _ries3nr = value;
        }
        public function get ries3nr():Boolean {
            return _ries3nr;
        }

        public function set ries4nr(value:Boolean):void {
            _ries4nr = value;
        }
        public function get ries4nr():Boolean {
            return _ries4nr;
        }

        public function set ries5nr(value:Boolean):void {
            _ries5nr = value;
        }
        public function get ries5nr():Boolean {
            return _ries5nr;
        }

        public function set ries6nr(value:Boolean):void {
            _ries6nr = value;
        }
        public function get ries6nr():Boolean {
            return _ries6nr;
        }

        public function set schlagPunkteGegner(value:String):void {
            _schlagPunkteGegner = value;
        }
        public function get schlagPunkteGegner():String {
            return _schlagPunkteGegner;
        }

        public function set showries1nr(value:Boolean):void {
            _showries1nr = value;
        }
        public function get showries1nr():Boolean {
            return _showries1nr;
        }

        public function set showries2nr(value:Boolean):void {
            _showries2nr = value;
        }
        public function get showries2nr():Boolean {
            return _showries2nr;
        }

        public function set showries3nr(value:Boolean):void {
            _showries3nr = value;
        }
        public function get showries3nr():Boolean {
            return _showries3nr;
        }

        public function set showries4nr(value:Boolean):void {
            _showries4nr = value;
        }
        public function get showries4nr():Boolean {
            return _showries4nr;
        }

        public function set showries5nr(value:Boolean):void {
            _showries5nr = value;
        }
        public function get showries5nr():Boolean {
            return _showries5nr;
        }

        public function set showries6nr(value:Boolean):void {
            _showries6nr = value;
        }
        public function get showries6nr():Boolean {
            return _showries6nr;
        }

        public function set spielArt(value:String):void {
            _spielArt = value;
        }
        public function get spielArt():String {
            return _spielArt;
        }

        public function set stunden(value:String):void {
            _stunden = value;
        }
        public function get stunden():String {
            return _stunden;
        }

        public function set totalNr(value:String):void {
            _totalNr = value;
        }
        public function get totalNr():String {
            return _totalNr;
        }

        public function set totalNrAlt(value:int):void {
            _totalNrAlt = value;
        }
        public function get totalNrAlt():int {
            return _totalNrAlt;
        }

        public function set totalNrHeim(value:String):void {
            _totalNrHeim = value;
        }
        public function get totalNrHeim():String {
            return _totalNrHeim;
        }

        public function readExternal(input:IDataInput):void {
            _datum = input.readObject() as String;
            _gegner = input.readObject() as String;
            _id = input.readObject() as int;
            _kampfrichter = input.readObject() as String;
            _kampfrichterGegner = input.readObject() as String;
            _minuten = input.readObject() as String;
            _name = input.readObject() as String;
            _ort = input.readObject() as String;
            _punkteId = input.readObject() as int;
            _ries1nr = input.readObject() as Boolean;
            _ries2nr = input.readObject() as Boolean;
            _ries3nr = input.readObject() as Boolean;
            _ries4nr = input.readObject() as Boolean;
            _ries5nr = input.readObject() as Boolean;
            _ries6nr = input.readObject() as Boolean;
            _schlagPunkteGegner = input.readObject() as String;
            _showries1nr = input.readObject() as Boolean;
            _showries2nr = input.readObject() as Boolean;
            _showries3nr = input.readObject() as Boolean;
            _showries4nr = input.readObject() as Boolean;
            _showries5nr = input.readObject() as Boolean;
            _showries6nr = input.readObject() as Boolean;
            _spielArt = input.readObject() as String;
            _stunden = input.readObject() as String;
            _totalNr = input.readObject() as String;
            _totalNrAlt = input.readObject() as int;
            _totalNrHeim = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_datum);
            output.writeObject(_gegner);
            output.writeObject(_id);
            output.writeObject(_kampfrichter);
            output.writeObject(_kampfrichterGegner);
            output.writeObject(_minuten);
            output.writeObject(_name);
            output.writeObject(_ort);
            output.writeObject(_punkteId);
            output.writeObject(_ries1nr);
            output.writeObject(_ries2nr);
            output.writeObject(_ries3nr);
            output.writeObject(_ries4nr);
            output.writeObject(_ries5nr);
            output.writeObject(_ries6nr);
            output.writeObject(_schlagPunkteGegner);
            output.writeObject(_showries1nr);
            output.writeObject(_showries2nr);
            output.writeObject(_showries3nr);
            output.writeObject(_showries4nr);
            output.writeObject(_showries5nr);
            output.writeObject(_showries6nr);
            output.writeObject(_spielArt);
            output.writeObject(_stunden);
            output.writeObject(_totalNr);
            output.writeObject(_totalNrAlt);
            output.writeObject(_totalNrHeim);
        }
    }
}