//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by BETRZLG.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDD_BETRZLG_FORM                101
#define IDD_BEARBEITENKONTO             102
#define IDP_FAILED_OPEN_DATABASE        103
#define IDD_BEARBEITENZLG               104
#define IDD_SEITEEINRICHTEN             105
#define IDD_OPTIONSDIALOG               106
#define IDD_DATUMDIALOG                 107
#define IDC_LISTBOX                     1000
#define IDC_PCNR                        1001
#define IDC_BANK                        1002
#define IDC_BETRAG                      1004
#define IDC_UNR1                        1005
#define IDC_UNR2                        1006
#define IDC_UNR3                        1007
#define IDC_UNR4                        1008
#define IDC_UNR5                        1009
#define IDC_UNR6                        1010
#define IDC_INHABER                     1011
#define IDC_ADD                         1012
#define IDC_AUFTRAGSNR                  1013
#define IDC_TOTAL                       1014
#define IDC_ANZAHL                      1015
#define IDC_ORAND                       1025
#define IDC_LRAND                       1026
#define IDC_RRAND                       1027
#define IDC_URAND                       1028
#define IDC_ZEILE1                      1029
#define IDC_ZEILE2                      1030
#define IDC_ZEILE3                      1031
#define IDC_ZEILE4                      1032
#define IDC_TAG                         1033
#define IDC_MONAT                       1034
#define IDC_JAHR                        1035
#define IDC_HISTNAME                    1036
#define ID_BEARBEITEN_LSCHEN            32771
#define ID_BEARBEITEN_ALLESLSCHEN       32772
#define ID_BEARBEITEN_WIEDERHOLEN       32773
#define ID_DATEI_DRUCKEN_INTERN         32774
#define ID_DATEI_DRUCKEN_EXTERN         32775
#define ID_DATEI_SEITENANSICHT_INTERN   32776
#define ID_DATEI_SEITENANSICHT_EXTERN   32777
#define ID_DATEI_SEITEEINRICHTEN        32778
#define ID_EXTRAS_OPTIONEN              32780
#define ID_DATEI_EXPORTIEREN            32781
#define ID_EXTRAS_HISTORY               32782

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1037
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
