  <misc:setProperty name="paging.banner.one_item_found"><bean:message key="paging.banner.one_items_found" arg0="{0}" /></misc:setProperty>
  <misc:setProperty name="paging.banner.all_items_found"><bean:message key="paging.banner.all_items_found" arg0="{0}" arg1="{1}" arg2="{2}" /></misc:setProperty>
  <misc:setProperty name="paging.banner.some_items_found"><bean:message key="paging.banner.some_items_found" arg0="{0}" arg1="{1}" arg2="{2}" arg3="{3}" /></misc:setProperty>

  <misc:setProperty name="paging.banner.full"><bean:message key="paging.banner.full" arg0="{0}" arg1="{1}" arg2="{2}" arg3="{3}" arg4="{4}"/></misc:setProperty>
  <misc:setProperty name="paging.banner.first"><bean:message key="paging.banner.first" arg0="{0}" arg1="{1}" arg2="{2}" arg3="{3}" arg4="{4}"/></misc:setProperty>
  <misc:setProperty name="paging.banner.last"><bean:message key="paging.banner.last" arg0="{0}" arg1="{1}" arg2="{2}" arg3="{3}" arg4="{4}"/></misc:setProperty>
