FROM alpine:3 as build
# install build tools
RUN apk add go
# cache dependencies
ADD go.mod go.sum ./
RUN go mod download
# build
ADD . .
RUN go build -o /convertpng .

# runtime
FROM alpine:3
RUN apk add --no-cache imagemagick
COPY --from=build /convertpng /convertpng
ENTRYPOINT [ "/convertpng" ]

