/*
 * Copyright the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ch.rasc.openai4j.images;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents the url or the content of an image generated by the OpenAI API.
 *
 */
public record Image(@JsonProperty("b64_json") String b64Json, String url,
		@JsonProperty("revised_prompt") String revisedPrompt) {

	/**
	 * The base64-encoded JSON of the generated image, if response_format is b64_json.
	 */
	@Override
	public String b64Json() {
		return this.b64Json;
	}

	/**
	 * The URL of the generated image, if response_format is url (default).
	 */
	@Override
	public String url() {
		return this.url;
	}

	/**
	 * The prompt that was used to generate the image, if there was any revision to the
	 * prompt.
	 */
	@Override
	public String revisedPrompt() {
		return this.revisedPrompt;
	}
}
