package ch.admin.astra.fabasoftadapter;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-30T12:30:52.027+01:00
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "FabasoftAdapter", 
                  wsdlLocation = "file:/D:/ws/geverdummy/src/main/wsdl/FabasoftAdapter.asmx.wsdl",
                  targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter") 
public class FabasoftAdapter extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.astra.admin.ch/FabasoftAdapter", "FabasoftAdapter");
    public final static QName FabasoftAdapterSoap12 = new QName("http://www.astra.admin.ch/FabasoftAdapter", "FabasoftAdapterSoap12");
    public final static QName FabasoftAdapterSoap = new QName("http://www.astra.admin.ch/FabasoftAdapter", "FabasoftAdapterSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/ws/geverdummy/src/main/wsdl/FabasoftAdapter.asmx.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FabasoftAdapter.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/ws/geverdummy/src/main/wsdl/FabasoftAdapter.asmx.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FabasoftAdapter(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FabasoftAdapter(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FabasoftAdapter() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns FabasoftAdapterSoap
     */
    @WebEndpoint(name = "FabasoftAdapterSoap12")
    public FabasoftAdapterSoap getFabasoftAdapterSoap12() {
        return super.getPort(FabasoftAdapterSoap12, FabasoftAdapterSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FabasoftAdapterSoap
     */
    @WebEndpoint(name = "FabasoftAdapterSoap12")
    public FabasoftAdapterSoap getFabasoftAdapterSoap12(WebServiceFeature... features) {
        return super.getPort(FabasoftAdapterSoap12, FabasoftAdapterSoap.class, features);
    }
    /**
     *
     * @return
     *     returns FabasoftAdapterSoap
     */
    @WebEndpoint(name = "FabasoftAdapterSoap")
    public FabasoftAdapterSoap getFabasoftAdapterSoap() {
        return super.getPort(FabasoftAdapterSoap, FabasoftAdapterSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FabasoftAdapterSoap
     */
    @WebEndpoint(name = "FabasoftAdapterSoap")
    public FabasoftAdapterSoap getFabasoftAdapterSoap(WebServiceFeature... features) {
        return super.getPort(FabasoftAdapterSoap, FabasoftAdapterSoap.class, features);
    }

}
