package ch.admin.astra.fabasoftadapter;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-30T12:30:51.959+01:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter", name = "FabasoftAdapterSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface FabasoftAdapterSoap {

    /**
     * Sucht nach Benutzern mit dem angegebenen Namen und/oder dem angegebenen Login. Einer der gefundenen Benutzer kann der Methode "SearchObjects" übergeben werden.
     */
    @WebResult(name = "SearchUsersResult", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
    @RequestWrapper(localName = "SearchUsers", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter", className = "ch.admin.astra.fabasoftadapter.SearchUsers")
    @WebMethod(operationName = "SearchUsers", action = "http://www.astra.admin.ch/FabasoftAdapter/SearchUsers")
    @ResponseWrapper(localName = "SearchUsersResponse", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter", className = "ch.admin.astra.fabasoftadapter.SearchUsersResponse")
    public ch.admin.astra.fabasoftadapter.ArrayOfString searchUsers(
        @WebParam(name = "name", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
        java.lang.String name,
        @WebParam(name = "login", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
        java.lang.String login
    );

    /**
     * Erstellt aus den übergebenen Parametern eine Fabasoft-Suche, erzeugt einen SOAPSearchRequest und setzt diesen gegen die Fabasoft Components WebServices ab. Das Resultat kann zwischen 0 und n XML-Strings liegen.
     */
    @WebResult(name = "SearchObjectsResult", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
    @RequestWrapper(localName = "SearchObjects", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter", className = "ch.admin.astra.fabasoftadapter.SearchObjects")
    @WebMethod(operationName = "SearchObjects", action = "http://www.astra.admin.ch/FabasoftAdapter/SearchObjects")
    @ResponseWrapper(localName = "SearchObjectsResponse", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter", className = "ch.admin.astra.fabasoftadapter.SearchObjectsResponse")
    public ch.admin.astra.fabasoftadapter.ArrayOfString searchObjects(
        @WebParam(name = "objclass", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
        java.lang.String objclass,
        @WebParam(name = "name", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
        java.lang.String name,
        @WebParam(name = "appkeys", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
        ch.admin.astra.fabasoftadapter.ArrayOfString appkeys,
        @WebParam(name = "createdat", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
        java.lang.String createdat,
        @WebParam(name = "changedat", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
        java.lang.String changedat,
        @WebParam(name = "owner", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
        java.lang.String owner,
        @WebParam(name = "root", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
        java.lang.String root
    );

    /**
     * Zur Zeit nicht implementiert.
     */
    @WebResult(name = "SetObjectResult", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
    @RequestWrapper(localName = "SetObject", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter", className = "ch.admin.astra.fabasoftadapter.SetObject")
    @WebMethod(operationName = "SetObject", action = "http://www.astra.admin.ch/FabasoftAdapter/SetObject")
    @ResponseWrapper(localName = "SetObjectResponse", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter", className = "ch.admin.astra.fabasoftadapter.SetObjectResponse")
    public boolean setObject(
        @WebParam(name = "objaddress", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
        java.lang.String objaddress,
        @WebParam(name = "xml", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
        java.lang.String xml
    );

    /**
     * Liest vom übergebenen Objekt die vordefinierten Eigenschaften (vollständiges RecordSet) aus. Wenn kein XML-Mapping in der Konfiguration spezifiziert ist, so tritt ein Fehler auf.
     */
    @WebResult(name = "GetObjectResult", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
    @RequestWrapper(localName = "GetObject", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter", className = "ch.admin.astra.fabasoftadapter.GetObject")
    @WebMethod(operationName = "GetObject", action = "http://www.astra.admin.ch/FabasoftAdapter/GetObject")
    @ResponseWrapper(localName = "GetObjectResponse", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter", className = "ch.admin.astra.fabasoftadapter.GetObjectResponse")
    public java.lang.String getObject(
        @WebParam(name = "objaddress", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
        java.lang.String objaddress
    );

    /**
     * Liefert den übergebenen String in GROSS-Buchstaben zurück
     */
    @WebResult(name = "TestResult", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
    @RequestWrapper(localName = "Test", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter", className = "ch.admin.astra.fabasoftadapter.Test")
    @WebMethod(operationName = "Test", action = "http://www.astra.admin.ch/FabasoftAdapter/Test")
    @ResponseWrapper(localName = "TestResponse", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter", className = "ch.admin.astra.fabasoftadapter.TestResponse")
    public ch.admin.astra.fabasoftadapter.ArrayOfString test(
        @WebParam(name = "val", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
        java.lang.String val
    );

    /**
     * Liest vom übergebenen Objekt die vordefinierten Eigenschaften (reduziertes RecordSet) aus. Wenn kein XML-Mapping in der Konfiguration spezifiziert ist, so tritt ein Fehler auf.
     */
    @WebResult(name = "GetFoundObjectResult", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
    @RequestWrapper(localName = "GetFoundObject", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter", className = "ch.admin.astra.fabasoftadapter.GetFoundObject")
    @WebMethod(operationName = "GetFoundObject", action = "http://www.astra.admin.ch/FabasoftAdapter/GetFoundObject")
    @ResponseWrapper(localName = "GetFoundObjectResponse", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter", className = "ch.admin.astra.fabasoftadapter.GetFoundObjectResponse")
    public java.lang.String getFoundObject(
        @WebParam(name = "objaddress", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
        java.lang.String objaddress
    );

    /**
     * Sucht nach Schlüsselwörter mit dem angegebenen Namen. Die gefundenen Schlüsselwörter können der Methode "SearchObjects" übergeben werden.
     */
    @WebResult(name = "SearchKeywordsResult", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
    @RequestWrapper(localName = "SearchKeywords", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter", className = "ch.admin.astra.fabasoftadapter.SearchKeywords")
    @WebMethod(operationName = "SearchKeywords", action = "http://www.astra.admin.ch/FabasoftAdapter/SearchKeywords")
    @ResponseWrapper(localName = "SearchKeywordsResponse", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter", className = "ch.admin.astra.fabasoftadapter.SearchKeywordsResponse")
    public ch.admin.astra.fabasoftadapter.ArrayOfString searchKeywords(
        @WebParam(name = "name", targetNamespace = "http://www.astra.admin.ch/FabasoftAdapter")
        java.lang.String name
    );
}
