/**
 * Generated by Gas3 v1.0.1 (Granite Data Services) on Fri Mar 28 07:46:14 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Info.as).
 */

package ch.ess.mp3search.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class InfoBase implements IExternalizable {

        private var _noOfSongs:Number;
        private var _totalDuration:Number;

        public function set noOfSongs(value:Number):void {
            _noOfSongs = value;
        }
        public function get noOfSongs():Number {
            return _noOfSongs;
        }

        public function set totalDuration(value:Number):void {
            _totalDuration = value;
        }
        public function get totalDuration():Number {
            return _totalDuration;
        }

        public function readExternal(input:IDataInput):void {
            _noOfSongs = input.readObject() as Number;
            _totalDuration = input.readObject() as Number;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_noOfSongs);
            output.writeObject(_totalDuration);
        }
    }
}