/**
 * Generated by Gas3 v1.0.1 (Granite Data Services) on Tue Mar 18 07:30:48 CET 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package ch.ess.mp3search.model {

    [Bindable]
    [RemoteClass(alias="ch.ess.mp3search.model.Songs")]
    public class Songs extends SongsBase {
      public var selected:Boolean;
    }
}