/**
 * Generated by Gas3 v1.0.1 (Granite Data Services) on Fri Mar 28 07:12:43 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Songs.as).
 */

package ch.ess.mp3search.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class SongsBase implements IExternalizable {

        private var _album:String;
        private var _artist:String;
        private var _directory:String;
        private var _duration:Number;
        private var _fileName:String;
        private var _genre:String;
        private var _title:String;
        private var _year:String;

        public function set album(value:String):void {
            _album = value;
        }
        public function get album():String {
            return _album;
        }

        public function set artist(value:String):void {
            _artist = value;
        }
        public function get artist():String {
            return _artist;
        }

        public function set directory(value:String):void {
            _directory = value;
        }
        public function get directory():String {
            return _directory;
        }

        public function set duration(value:Number):void {
            _duration = value;
        }
        public function get duration():Number {
            return _duration;
        }

        public function set fileName(value:String):void {
            _fileName = value;
        }
        public function get fileName():String {
            return _fileName;
        }

        public function set genre(value:String):void {
            _genre = value;
        }
        public function get genre():String {
            return _genre;
        }

        public function set title(value:String):void {
            _title = value;
        }
        public function get title():String {
            return _title;
        }

        public function set year(value:String):void {
            _year = value;
        }
        public function get year():String {
            return _year;
        }

        public function readExternal(input:IDataInput):void {
            _album = input.readObject() as String;
            _artist = input.readObject() as String;
            _directory = input.readObject() as String;
            _duration = input.readObject() as Number;
            _fileName = input.readObject() as String;
            _genre = input.readObject() as String;
            _title = input.readObject() as String;
            _year = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_album);
            output.writeObject(_artist);
            output.writeObject(_directory);
            output.writeObject(_duration);
            output.writeObject(_fileName);
            output.writeObject(_genre);
            output.writeObject(_title);
            output.writeObject(_year);
        }
    }
}