/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Wed Jul 16 16:57:30 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Comments.as).
 */

package ch.ess.issue.entity {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.meta;
    import org.granite.tide.IPropertyHolder;

    use namespace meta;

    [Managed]
    public class CommentsBase extends AbstractEntity {

        private var _comment:String;
        private var _commentDate:Date;
        private var _issue:Issue;
        private var _user:User;

        public function set comment(value:String):void {
            _comment = value;
        }
        public function get comment():String {
            return _comment;
        }

        public function set commentDate(value:Date):void {
            _commentDate = value;
        }
        public function get commentDate():Date {
            return _commentDate;
        }

        public function set issue(value:Issue):void {
            _issue = value;
        }
        public function get issue():Issue {
            return _issue;
        }

        public function set user(value:User):void {
            _user = value;
        }
        public function get user():User {
            return _user;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            if (meta::isInitialized()) {
                _comment = input.readObject() as String;
                _commentDate = input.readObject() as Date;
                _issue = input.readObject() as Issue;
                _user = input.readObject() as User;
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            if (meta::isInitialized()) {
                if (_comment is IPropertyHolder)
                    output.writeObject(IPropertyHolder(_comment).object);
                else
                    output.writeObject(_comment);
                if (_commentDate is IPropertyHolder)
                    output.writeObject(IPropertyHolder(_commentDate).object);
                else
                    output.writeObject(_commentDate);
                if (_issue is IPropertyHolder)
                    output.writeObject(IPropertyHolder(_issue).object);
                else
                    output.writeObject(_issue);
                if (_user is IPropertyHolder)
                    output.writeObject(IPropertyHolder(_user).object);
                else
                    output.writeObject(_user);
            }
        }
    }
}
