/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Wed Jul 16 16:57:30 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Project.as).
 */

package ch.ess.issue.entity {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;
    import org.granite.meta;
    import org.granite.tide.IPropertyHolder;

    use namespace meta;

    [Managed]
    public class ProjectBase extends AbstractEntity {

        private var _components:ListCollectionView;
        private var _customer:Customer;
        private var _name:String;

        public function set components(value:ListCollectionView):void {
            _components = value;
        }
        public function get components():ListCollectionView {
            return _components;
        }

        public function set customer(value:Customer):void {
            _customer = value;
        }
        public function get customer():Customer {
            return _customer;
        }

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            if (meta::isInitialized()) {
                _components = input.readObject() as ListCollectionView;
                _customer = input.readObject() as Customer;
                _name = input.readObject() as String;
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            if (meta::isInitialized()) {
                if (_components is IPropertyHolder)
                    output.writeObject(IPropertyHolder(_components).object);
                else
                    output.writeObject(_components);
                if (_customer is IPropertyHolder)
                    output.writeObject(IPropertyHolder(_customer).object);
                else
                    output.writeObject(_customer);
                if (_name is IPropertyHolder)
                    output.writeObject(IPropertyHolder(_name).object);
                else
                    output.writeObject(_name);
            }
        }
    }
}
