/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Wed Jul 16 16:57:30 CEST 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package ch.ess.issue.entity {

    [Bindable]
    [RemoteClass(alias="ch.ess.issue.entity.Resolution")]
    public class Resolution extends ResolutionBase {
    }
}