/**
 * Generated by Gas3 v1.0.0 (Granite Data Services) on Wed Feb 06 10:17:13 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Many.as).
 */

package ch.ess.onemany.entity {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class ManyBase extends AbstractEntity {

        private var _name:String;
        private var _one:One;

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function set one(value:One):void {
            _one = value;
        }
        public function get one():One {
            return _one;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            if (meta::isInitialized()) {
                _name = input.readObject() as String;
                _one = input.readObject() as One;
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            if (meta::isInitialized()) {
                output.writeObject(_name);
                output.writeObject(_one);
            }
        }
    }
}