/**
 * Generated by Gas3 v1.0.0 (Granite Data Services) on Wed Feb 06 10:17:13 CET 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package ch.ess.onemany.entity {

    [Bindable]
    [RemoteClass(alias="ch.ess.onemany.entity.One")]
    public class One extends OneBase {
    }
}