/**
 * Generated by Gas3 v1.0.0 (Granite Data Services) on Wed Feb 06 10:17:13 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (One.as).
 */

package ch.ess.onemany.entity {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ArrayCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class OneBase extends AbstractEntity {

        private var _many:ArrayCollection;
        private var _name:String;

        public function set many(value:ArrayCollection):void {
            _many = value;
        }
        public function get many():ArrayCollection {
            return _many;
        }

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            if (meta::isInitialized()) {
                _many = input.readObject() as ArrayCollection;
                _name = input.readObject() as String;
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            if (meta::isInitialized()) {
                output.writeObject(_many);
                output.writeObject(_name);
            }
        }
    }
}