//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.30 at 12:40:05 PM CET 
//


package ch.admin.astra.fabasoftadapter.cnatperson;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import ch.admin.astra.fabasoftadapter.cdocument.ObjectType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the admin.astra.fabasoftadapter.cnatperson package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CNATPERSON_QNAME = new QName("urn:schemas.fabasoft.com:CNATPERSON", "CNATPERSON");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: admin.astra.fabasoftadapter.cnatperson
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CNATPERSONType }
     * 
     */
    public CNATPERSONType createCNATPERSONType() {
        return new CNATPERSONType();
    }

    /**
     * Create an instance of {@link ObjectType }
     * 
     */
    public ObjectType createObjectType() {
        return new ObjectType();
    }

    /**
     * Create an instance of {@link HauptadresseType }
     * 
     */
    public HauptadresseType createHauptadresseType() {
        return new HauptadresseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CNATPERSONType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas.fabasoft.com:CNATPERSON", name = "CNATPERSON")
    public JAXBElement<CNATPERSONType> createCNATPERSON(CNATPERSONType value) {
        return new JAXBElement<CNATPERSONType>(_CNATPERSON_QNAME, CNATPERSONType.class, null, value);
    }

}
