server:
  port: 80
  compression:
     enabled: true
     mime-types: text/html,text/xml,text/plain,text/css,application/json,application/javascript

spring:
  resources:
    cache:
      period: 31556926
    
logging:
  level:
    org.springframework: WARN
    org.hibernate: WARN
    org.apache: WARN
    ch: WARN
