

/*
 * Source generated by VBSF using template2.tmpl.
 */

package ch.sr.lottowin.db;

import com.objectmatter.bsf.*;

/**
 * Class Joker.
 */
public class Joker {

    /* attributes */
    private Long id;
    private OReference userid;
    private String joker;

    /** Creates a new Joker */    
    public Joker() {
        super();
    }
    /** Creates a new Joker with the supplied values */ 
    public Joker( Long newid,
                  String newjoker) {
          id = newid;
          joker = newjoker;
    }
    
    
    /** Accessor for attribute id */
    public Long getId() {
        return id;
    }
    
    /** Accessor for attribute joker */
    public String getJoker() {
        return joker;
    }
    
    /** Mutator for attribute id */
    public void setId(Long newId) {
        id = newId;
    }
    
    /** Mutator for attribute joker */
    public void setJoker(String newJoker) {
        joker = newJoker;
    }
    
    /** Accessor for reference userid */
    public User getUserid() throws BODBException {
        return (User)userid.get();
    }
    
    /** Mutator for reference userid */
    public void setUserid(User newUserid)
      throws BODBException, BOReferenceNotUpdatedException, BOUpdateConflictException {
        userid.set(newUserid);
    }
    
    
    
    
}



