

/*
 * Source generated by VBSF using template2.tmpl.
 */

package ch.sr.lottowin.db;

import com.objectmatter.bsf.*;

/**
 * Class Tip.
 */
public class Tip {

    /* attributes */
    private Long id;
    private OReference user;
    private Long z1;
    private Long z2;
    private Long z3;
    private Long z4;
    private Long z5;
    private Long z6;

    /** Creates a new Tip */    
    public Tip() {
        super();
    }
    /** Creates a new Tip with the supplied values */ 
    public Tip( Long newid,
                Long newz1,
                Long newz2,
                Long newz3,
                Long newz4,
                Long newz5,
                Long newz6) {
          id = newid;
          z1 = newz1;
          z2 = newz2;
          z3 = newz3;
          z4 = newz4;
          z5 = newz5;
          z6 = newz6;
    }
    
    
    /** Accessor for attribute id */
    public Long getId() {
        return id;
    }
    
    /** Accessor for attribute z1 */
    public Long getZ1() {
        return z1;
    }
    
    /** Accessor for attribute z2 */
    public Long getZ2() {
        return z2;
    }
    
    /** Accessor for attribute z3 */
    public Long getZ3() {
        return z3;
    }
    
    /** Accessor for attribute z4 */
    public Long getZ4() {
        return z4;
    }
    
    /** Accessor for attribute z5 */
    public Long getZ5() {
        return z5;
    }
    
    /** Accessor for attribute z6 */
    public Long getZ6() {
        return z6;
    }
    
    /** Mutator for attribute id */
    public void setId(Long newId) {
        id = newId;
    }
    
    /** Mutator for attribute z1 */
    public void setZ1(Long newZ1) {
        z1 = newZ1;
    }
    
    /** Mutator for attribute z2 */
    public void setZ2(Long newZ2) {
        z2 = newZ2;
    }
    
    /** Mutator for attribute z3 */
    public void setZ3(Long newZ3) {
        z3 = newZ3;
    }
    
    /** Mutator for attribute z4 */
    public void setZ4(Long newZ4) {
        z4 = newZ4;
    }
    
    /** Mutator for attribute z5 */
    public void setZ5(Long newZ5) {
        z5 = newZ5;
    }
    
    /** Mutator for attribute z6 */
    public void setZ6(Long newZ6) {
        z6 = newZ6;
    }
    
    /** Accessor for reference user */
    public User getUser() throws BODBException {
        return (User)user.get();
    }
    
    /** Mutator for reference user */
    public void setUser(User newUser)
      throws BODBException, BOReferenceNotUpdatedException, BOUpdateConflictException {
        user.set(newUser);
    }
    
    
  public long[] getZArray() {
    long[] zarray = new long[6];
    zarray[0] = z1.longValue();
    zarray[1] = z2.longValue();
    zarray[2] = z3.longValue();
    zarray[3] = z4.longValue();
    zarray[4] = z5.longValue();
    zarray[5] = z6.longValue();
    return zarray;
  }    
    
}



