

/*
 * Source generated by VBSF using template2.tmpl.
 */

package ch.ess.addressbook.db;

import com.objectmatter.bsf.*;
import java.util.*;
import java.math.BigDecimal;

/**
 * Class Contact.
 */
public class Contact {

    /* attributes */
    public Integer contactId;
    public String firstName;
    public String name;
    public String company;
    public String address;
    public String plz;
    public String city;
    public String country;
    public String email;
    public String mobil;
    public String businessPhone;
    public String privatePhone;
    public OCollection contactAttribute;

    /** Creates a new Contact */    
    public Contact() {
        super();
    }
    /** Creates a new Contact with the supplied values */ 
    public Contact( Integer newcontactId,
                    String newfirstName,
                    String newname,
                    String newcompany,
                    String newaddress,
                    String newplz,
                    String newcity,
                    String newcountry,
                    String newemail,
                    String newmobil,
                    String newbusinessPhone,
                    String newprivatePhone) {
          contactId = newcontactId;
          firstName = newfirstName;
          name = newname;
          company = newcompany;
          address = newaddress;
          plz = newplz;
          city = newcity;
          country = newcountry;
          email = newemail;
          mobil = newmobil;
          businessPhone = newbusinessPhone;
          privatePhone = newprivatePhone;
    }
    
    
    /** Accessor for attribute contactId */
    public Integer getContactId() {
        return contactId;
    }
    
    /** Accessor for attribute firstName */
    public String getFirstName() {
        return firstName;
    }
    
    /** Accessor for attribute name */
    public String getName() {
        return name;
    }
    
    /** Accessor for attribute company */
    public String getCompany() {
        return company;
    }
    
    /** Accessor for attribute address */
    public String getAddress() {
        return address;
    }
    
    /** Accessor for attribute plz */
    public String getPlz() {
        return plz;
    }
    
    /** Accessor for attribute city */
    public String getCity() {
        return city;
    }
    
    /** Accessor for attribute country */
    public String getCountry() {
        return country;
    }
    
    /** Accessor for attribute email */
    public String getEmail() {
        return email;
    }
    
    /** Accessor for attribute mobil */
    public String getMobil() {
        return mobil;
    }
    
    /** Accessor for attribute businessPhone */
    public String getBusinessPhone() {
        return businessPhone;
    }
    
    /** Accessor for attribute privatePhone */
    public String getPrivatePhone() {
        return privatePhone;
    }
    
    /** Mutator for attribute contactId */
    public void setContactId(Integer newContactId) {
        contactId = newContactId;
    }
    
    /** Mutator for attribute firstName */
    public void setFirstName(String newFirstName) {
        firstName = newFirstName;
    }
    
    /** Mutator for attribute name */
    public void setName(String newName) {
        name = newName;
    }
    
    /** Mutator for attribute company */
    public void setCompany(String newCompany) {
        company = newCompany;
    }
    
    /** Mutator for attribute address */
    public void setAddress(String newAddress) {
        address = newAddress;
    }
    
    /** Mutator for attribute plz */
    public void setPlz(String newPlz) {
        plz = newPlz;
    }
    
    /** Mutator for attribute city */
    public void setCity(String newCity) {
        city = newCity;
    }
    
    /** Mutator for attribute country */
    public void setCountry(String newCountry) {
        country = newCountry;
    }
    
    /** Mutator for attribute email */
    public void setEmail(String newEmail) {
        email = newEmail;
    }
    
    /** Mutator for attribute mobil */
    public void setMobil(String newMobil) {
        mobil = newMobil;
    }
    
    /** Mutator for attribute businessPhone */
    public void setBusinessPhone(String newBusinessPhone) {
        businessPhone = newBusinessPhone;
    }
    
    /** Mutator for attribute privatePhone */
    public void setPrivatePhone(String newPrivatePhone) {
        privatePhone = newPrivatePhone;
    }
    
    
    
    
    /** Returns all elements in the ContactAttribute collection */
    public ContactAttribute[] getContactAttribute() throws BODBException {
        return (ContactAttribute[])contactAttribute.get();
    }
    
    /** Adds the supplied element to the ContactAttribute collection */
    public void addContactAttribute(ContactAttribute newContactAttribute)
      throws BODBException, BOReferenceNotUpdatedException, BOUpdateConflictException {
        contactAttribute.add(newContactAttribute);
    }
    
    /** Removes the supplied element from the ContactAttribute collection */
    public void removeContactAttribute(ContactAttribute oldContactAttribute)
      throws BODBException, BOReferenceNotUpdatedException, BOUpdateConflictException {
        contactAttribute.remove(oldContactAttribute);
    }
}



