

/*
 * Source generated by VBSF using template2.tmpl.
 */

package ch.ess.addressbook.db;

import com.objectmatter.bsf.*;
import java.util.*;
import java.math.BigDecimal;

/**
 * Class ContactAttribute.
 */
public class ContactAttribute {

    /* attributes */
    public Integer contactAttributeId;
    public OReference contact;
    public String key;
    public String value;

    /** Creates a new ContactAttribute */    
    public ContactAttribute() {
        super();
    }
    /** Creates a new ContactAttribute with the supplied values */ 
    public ContactAttribute( Integer newcontactAttributeId,
                             String newkey,
                             String newvalue) {
          contactAttributeId = newcontactAttributeId;
          key = newkey;
          value = newvalue;
    }
    
    
    /** Accessor for attribute contactAttributeId */
    public Integer getContactAttributeId() {
        return contactAttributeId;
    }
    
    /** Accessor for attribute key */
    public String getKey() {
        return key;
    }
    
    /** Accessor for attribute value */
    public String getValue() {
        return value;
    }
    
    /** Mutator for attribute contactAttributeId */
    public void setContactAttributeId(Integer newContactAttributeId) {
        contactAttributeId = newContactAttributeId;
    }
    
    /** Mutator for attribute key */
    public void setKey(String newKey) {
        key = newKey;
    }
    
    /** Mutator for attribute value */
    public void setValue(String newValue) {
        value = newValue;
    }
    
    /** Accessor for reference contact */
    public Contact getcontact() throws BODBException {
        return (Contact)contact.get();
    }
    
    /** Mutator for reference contact */
    public void setcontact(Contact newcontact)
      throws BODBException, BOReferenceNotUpdatedException, BOUpdateConflictException {
        contact.set(newcontact);
    }
    
    
    
    
}



