package ch.ess.test;

// Generated 13-Jul-2006 12:08:02 by Hibernate Tools 3.1.0.beta5

/**
 * Car2 generated by hbm2java
 */
public class Car2 implements java.io.Serializable {

  // Fields    

  private Car2Id id;

  // Constructors

  /** default constructor */
  public Car2() {
  }

  /** full constructor */
  public Car2(Car2Id id) {
    this.id = id;
  }

  // Property accessors
  public Car2Id getId() {
    return this.id;
  }

  public void setId(Car2Id id) {
    this.id = id;
  }

}
