package ch.ess.test;

// Generated 13-Jul-2006 12:08:02 by Hibernate Tools 3.1.0.beta5

import java.util.Date;

/**
 * Car2Id generated by hbm2java
 */
public class Car2Id implements java.io.Serializable {

  // Fields    

  private int id;
  private int version;
  private String name;
  private Date date;
  private Integer abzahlung;
  private Byte aktiv;
  private String name2;

  // Constructors

  /** default constructor */
  public Car2Id() {
  }

  /** minimal constructor */
  public Car2Id(int id, int version) {
    this.id = id;
    this.version = version;
  }

  /** full constructor */
  public Car2Id(int id, int version, String name, Date date, Integer abzahlung, Byte aktiv, String name2) {
    this.id = id;
    this.version = version;
    this.name = name;
    this.date = date;
    this.abzahlung = abzahlung;
    this.aktiv = aktiv;
    this.name2 = name2;
  }

  // Property accessors
  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public int getVersion() {
    return this.version;
  }

  public void setVersion(int version) {
    this.version = version;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Date getDate() {
    return this.date;
  }

  public void setDate(Date date) {
    this.date = date;
  }

  public Integer getAbzahlung() {
    return this.abzahlung;
  }

  public void setAbzahlung(Integer abzahlung) {
    this.abzahlung = abzahlung;
  }

  public Byte getAktiv() {
    return this.aktiv;
  }

  public void setAktiv(Byte aktiv) {
    this.aktiv = aktiv;
  }

  public String getName2() {
    return this.name2;
  }

  public void setName2(String name2) {
    this.name2 = name2;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof Car2Id))
      return false;
    Car2Id castOther = (Car2Id)other;

    return (this.getId() == castOther.getId())
        && (this.getVersion() == castOther.getVersion())
        && ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null && this
            .getName().equals(castOther.getName())))
        && ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null && this
            .getDate().equals(castOther.getDate())))
        && ((this.getAbzahlung() == castOther.getAbzahlung()) || (this.getAbzahlung() != null
            && castOther.getAbzahlung() != null && this.getAbzahlung().equals(castOther.getAbzahlung())))
        && ((this.getAktiv() == castOther.getAktiv()) || (this.getAktiv() != null && castOther.getAktiv() != null && this
            .getAktiv().equals(castOther.getAktiv())))
        && ((this.getName2() == castOther.getName2()) || (this.getName2() != null && castOther.getName2() != null && this
            .getName2().equals(castOther.getName2())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + this.getId();
    result = 37 * result + this.getVersion();
    result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
    result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
    result = 37 * result + (getAbzahlung() == null ? 0 : this.getAbzahlung().hashCode());
    result = 37 * result + (getAktiv() == null ? 0 : this.getAktiv().hashCode());
    result = 37 * result + (getName2() == null ? 0 : this.getName2().hashCode());
    return result;
  }

}
