/**
 * Generated by Gas3 v1.0.0 (Granite Data Services) on Mon Jan 21 05:58:50 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Club.as).
 */

package ch.ess.hgtracker.db {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ArrayCollection;
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class ClubBase implements IExternalizable {

        private var __laziness:String = null;

        private var _admin:Boolean;
        private var _art:ArrayCollection;
        private var _benutzername:String;
        private var _hgName:String;
        private var _id:Number;
        private var _ort:String;
        private var _passwort:String;
        private var _plz:String;
        private var _praesident:String;
        private var _punkteMS:Number;
        private var _sessionId:String;
        private var _spiele:ArrayCollection;
        private var _spieler:ArrayCollection;
        private var _strasse:String;
        private var _webLogin:String;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is Club) || (property as Club).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set admin(value:Boolean):void {
            _admin = value;
        }
        public function get admin():Boolean {
            return _admin;
        }

        public function set art(value:ArrayCollection):void {
            _art = value;
        }
        public function get art():ArrayCollection {
            return _art;
        }

        public function set benutzername(value:String):void {
            _benutzername = value;
        }
        public function get benutzername():String {
            return _benutzername;
        }

        public function set hgName(value:String):void {
            _hgName = value;
        }
        public function get hgName():String {
            return _hgName;
        }

        public function set id(value:Number):void {
            _id = value;
        }
        public function get id():Number {
            return _id;
        }

        public function set ort(value:String):void {
            _ort = value;
        }
        public function get ort():String {
            return _ort;
        }

        public function set passwort(value:String):void {
            _passwort = value;
        }
        public function get passwort():String {
            return _passwort;
        }

        public function set plz(value:String):void {
            _plz = value;
        }
        public function get plz():String {
            return _plz;
        }

        public function set praesident(value:String):void {
            _praesident = value;
        }
        public function get praesident():String {
            return _praesident;
        }

        public function set punkteMS(value:Number):void {
            _punkteMS = value;
        }
        public function get punkteMS():Number {
            return _punkteMS;
        }

        public function set sessionId(value:String):void {
            _sessionId = value;
        }
        public function get sessionId():String {
            return _sessionId;
        }

        public function set spiele(value:ArrayCollection):void {
            _spiele = value;
        }
        public function get spiele():ArrayCollection {
            return _spiele;
        }

        public function set spieler(value:ArrayCollection):void {
            _spieler = value;
        }
        public function get spieler():ArrayCollection {
            return _spieler;
        }

        public function set strasse(value:String):void {
            _strasse = value;
        }
        public function get strasse():String {
            return _strasse;
        }

        public function set webLogin(value:String):void {
            _webLogin = value;
        }
        public function get webLogin():String {
            return _webLogin;
        }

        public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                _admin = input.readObject() as Boolean;
                _art = input.readObject() as ArrayCollection;
                _benutzername = input.readObject() as String;
                _hgName = input.readObject() as String;
                _id = input.readObject() as Number;
                _ort = input.readObject() as String;
                _passwort = input.readObject() as String;
                _plz = input.readObject() as String;
                _praesident = input.readObject() as String;
                _punkteMS = input.readObject() as Number;
                _sessionId = input.readObject() as String;
                _spiele = input.readObject() as ArrayCollection;
                _spieler = input.readObject() as ArrayCollection;
                _strasse = input.readObject() as String;
                _webLogin = input.readObject() as String;
            }
            else {
                _id = input.readObject() as Number;
            }
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                output.writeObject(_admin);
                output.writeObject(_art);
                output.writeObject(_benutzername);
                output.writeObject(_hgName);
                output.writeObject(_id);
                output.writeObject(_ort);
                output.writeObject(_passwort);
                output.writeObject(_plz);
                output.writeObject(_praesident);
                output.writeObject(_punkteMS);
                output.writeObject(_sessionId);
                output.writeObject(_spiele);
                output.writeObject(_spieler);
                output.writeObject(_strasse);
                output.writeObject(_webLogin);
            }
            else {
                output.writeObject(_id);
            }
        }
    }
}