/**
 * Generated by Gas3 v1.0.0 (Granite Data Services) on Mon Jan 21 05:58:50 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Spiel.as).
 */

package ch.ess.hgtracker.db {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ArrayCollection;
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class SpielBase implements IExternalizable {

        private var __laziness:String = null;

        private var _anzahlRies:Number;
        private var _art:Art;
        private var _artName:String;
        private var _club:Club;
        private var _datum:Date;
        private var _gegner:String;
        private var _hasAufstellung:Boolean;
        private var _id:Number;
        private var _kampfrichter:String;
        private var _kampfrichterGegner:String;
        private var _ort:String;
        private var _punkte:ArrayCollection;
        private var _schlagPunkte:Number;
        private var _schlagPunkteGegner:Number;
        private var _totalNr:Number;
        private var _totalNrGegner:Number;
        private var _wochentag:String;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __laziness === null;

            var property:* = this[name];
            return (
                (!(property is Spiel) || (property as Spiel).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        public function set anzahlRies(value:Number):void {
            _anzahlRies = value;
        }
        public function get anzahlRies():Number {
            return _anzahlRies;
        }

        public function set art(value:Art):void {
            _art = value;
        }
        public function get art():Art {
            return _art;
        }

        public function set artName(value:String):void {
            _artName = value;
        }
        public function get artName():String {
            return _artName;
        }

        public function set club(value:Club):void {
            _club = value;
        }
        public function get club():Club {
            return _club;
        }

        public function set datum(value:Date):void {
            _datum = value;
        }
        public function get datum():Date {
            return _datum;
        }

        public function set gegner(value:String):void {
            _gegner = value;
        }
        public function get gegner():String {
            return _gegner;
        }

        public function set hasAufstellung(value:Boolean):void {
            _hasAufstellung = value;
        }
        public function get hasAufstellung():Boolean {
            return _hasAufstellung;
        }

        public function set id(value:Number):void {
            _id = value;
        }
        public function get id():Number {
            return _id;
        }

        public function set kampfrichter(value:String):void {
            _kampfrichter = value;
        }
        public function get kampfrichter():String {
            return _kampfrichter;
        }

        public function set kampfrichterGegner(value:String):void {
            _kampfrichterGegner = value;
        }
        public function get kampfrichterGegner():String {
            return _kampfrichterGegner;
        }

        public function set ort(value:String):void {
            _ort = value;
        }
        public function get ort():String {
            return _ort;
        }

        public function set punkte(value:ArrayCollection):void {
            _punkte = value;
        }
        public function get punkte():ArrayCollection {
            return _punkte;
        }

        public function set schlagPunkte(value:Number):void {
            _schlagPunkte = value;
        }
        public function get schlagPunkte():Number {
            return _schlagPunkte;
        }

        public function set schlagPunkteGegner(value:Number):void {
            _schlagPunkteGegner = value;
        }
        public function get schlagPunkteGegner():Number {
            return _schlagPunkteGegner;
        }

        public function set totalNr(value:Number):void {
            _totalNr = value;
        }
        public function get totalNr():Number {
            return _totalNr;
        }

        public function set totalNrGegner(value:Number):void {
            _totalNrGegner = value;
        }
        public function get totalNrGegner():Number {
            return _totalNrGegner;
        }

        public function set wochentag(value:String):void {
            _wochentag = value;
        }
        public function get wochentag():String {
            return _wochentag;
        }

        public function readExternal(input:IDataInput):void {
            __laziness = input.readObject() as String;
            if (meta::isInitialized()) {
                _anzahlRies = input.readObject() as Number;
                _art = input.readObject() as Art;
                _artName = input.readObject() as String;
                _club = input.readObject() as Club;
                _datum = input.readObject() as Date;
                _gegner = input.readObject() as String;
                _hasAufstellung = input.readObject() as Boolean;
                _id = input.readObject() as Number;
                _kampfrichter = input.readObject() as String;
                _kampfrichterGegner = input.readObject() as String;
                _ort = input.readObject() as String;
                _punkte = input.readObject() as ArrayCollection;
                _schlagPunkte = input.readObject() as Number;
                _schlagPunkteGegner = input.readObject() as Number;
                _totalNr = input.readObject() as Number;
                _totalNrGegner = input.readObject() as Number;
                _wochentag = input.readObject() as String;
            }
            else {
                _id = input.readObject() as Number;
            }
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(__laziness);
            if (meta::isInitialized()) {
                output.writeObject(_anzahlRies);
                output.writeObject(_art);
                output.writeObject(_artName);
                output.writeObject(_club);
                output.writeObject(_datum);
                output.writeObject(_gegner);
                output.writeObject(_hasAufstellung);
                output.writeObject(_id);
                output.writeObject(_kampfrichter);
                output.writeObject(_kampfrichterGegner);
                output.writeObject(_ort);
                output.writeObject(_punkte);
                output.writeObject(_schlagPunkte);
                output.writeObject(_schlagPunkteGegner);
                output.writeObject(_totalNr);
                output.writeObject(_totalNrGegner);
                output.writeObject(_wochentag);
            }
            else {
                output.writeObject(_id);
            }
        }
    }
}