/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sun Jun 22 12:23:37 CEST 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package ch.ess.testtracker.entity {

    [Bindable]
    [RemoteClass(alias="ch.ess.testtracker.entity.AbstractEntity")]
    public class AbstractEntity extends AbstractEntityBase {
    }
}