//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.30 at 12:39:25 PM CET 
//


package ch.admin.astra.fabasoftadapter.cdocument;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the admin.astra.fabasoftadapter.cdocument package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CDOCUMENT_QNAME = new QName("urn:schemas.fabasoft.com:CDOCUMENT", "CDOCUMENT");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: admin.astra.fabasoftadapter.cdocument
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CDOCUMENTType }
     * 
     */
    public CDOCUMENTType createCDOCUMENTType() {
        return new CDOCUMENTType();
    }

    /**
     * Create an instance of {@link ObjectType }
     * 
     */
    public ObjectType createObjectType() {
        return new ObjectType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CDOCUMENTType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas.fabasoft.com:CDOCUMENT", name = "CDOCUMENT")
    public JAXBElement<CDOCUMENTType> createCDOCUMENT(CDOCUMENTType value) {
        return new JAXBElement<CDOCUMENTType>(_CDOCUMENT_QNAME, CDOCUMENTType.class, null, value);
    }

}
