/**
 * Generated by Gas3 v1.0.0 (Granite Data Services) on Mon Jan 21 12:48:32 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (TextResource.as).
 */

package ch.ess.hpadmin.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class TextResourceBase implements IExternalizable {

        private var _fieldId:Number;
        private var _fieldName:String;
        private var _textDe:String;
        private var _textDeId:Number;
        private var _textEn:String;
        private var _textEnId:Number;

        public function set fieldId(value:Number):void {
            _fieldId = value;
        }
        public function get fieldId():Number {
            return _fieldId;
        }

        public function set fieldName(value:String):void {
            _fieldName = value;
        }
        public function get fieldName():String {
            return _fieldName;
        }

        public function set textDe(value:String):void {
            _textDe = value;
        }
        public function get textDe():String {
            return _textDe;
        }

        public function set textDeId(value:Number):void {
            _textDeId = value;
        }
        public function get textDeId():Number {
            return _textDeId;
        }

        public function set textEn(value:String):void {
            _textEn = value;
        }
        public function get textEn():String {
            return _textEn;
        }

        public function set textEnId(value:Number):void {
            _textEnId = value;
        }
        public function get textEnId():Number {
            return _textEnId;
        }

        public function readExternal(input:IDataInput):void {
            _fieldId = input.readObject() as Number;
            _fieldName = input.readObject() as String;
            _textDe = input.readObject() as String;
            _textDeId = input.readObject() as Number;
            _textEn = input.readObject() as String;
            _textEnId = input.readObject() as Number;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_fieldId);
            output.writeObject(_fieldName);
            output.writeObject(_textDe);
            output.writeObject(_textDeId);
            output.writeObject(_textEn);
            output.writeObject(_textEnId);
        }
    }
}