//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by CISNODES.RC
//
#define IDR_MAIN_ICON                   2
#define IDR_MAIN_ACCEL                  3
#define IDD_ABOUTBOX                    100
#define MAIN_DLG_WINDOW                 101
#define IDR_MAIN_MENU                   102   
#define IDC_EDIT								 103
#define IDC_NODE								 104
#define IDC_EXIT                        105
#define IDC_ABOUT                       106
#define IDC_SUCHEN                      107 
#define IDC_TOPMOST							 108
#define ID_ABOUT                        32771
#define ID_DIALOGS_FILEOPEN             32773
#define ID_DIALOGS_FILESAVE             32774
#define ID_DIALOGS_FONT                 32775
#define ID_DIALOGS_COLOR                32776
#define ID_DIALOGS_PRINT                32777
#define ID_DIALOGS_ABOUT                32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
