
package ch.admin.ws.zas.regcent.upi._0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ch.ech.xmlns.ech_0086._1.CompareDataRequest;
import ch.ech.xmlns.ech_0086._1.CompareDataResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UPICompareServicePortType", targetNamespace = "http://ws.admin.ch/zas/regcent/UPI/0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ch.ech.xmlns.ech_0086._1.ObjectFactory.class,
    ch.ech.xmlns.ech_0071._1.ObjectFactory.class,
    ch.ech.xmlns.ech_0090._1.ObjectFactory.class,
    ch.ech.xmlns.ech_0084._1.ObjectFactory.class,
    ch.ech.xmlns.ech_0044._1.ObjectFactory.class,
    ch.ech.xmlns.ech_0011._3.ObjectFactory.class,
    ch.ech.xmlns.ech_0006._2.ObjectFactory.class,
    ch.ech.xmlns.ech_0007._3.ObjectFactory.class,
    ch.ech.xmlns.ech_0008._2.ObjectFactory.class,
    ch.ech.xmlns.ech_0010._3.ObjectFactory.class,
    ch.ech.xmlns.ech_0072._1.ObjectFactory.class
})
public interface UPICompareServicePortType {


    /**
     * 
     * @param body
     * @return
     *     returns ch.ech.xmlns.ech_0086._1.CompareDataResponse
     */
    @WebMethod(action = "http://soap.upi.admin.ch")
    @WebResult(name = "compareDataResponse", targetNamespace = "http://www.ech.ch/xmlns/eCH-0086/1", partName = "body")
    public CompareDataResponse compareData(
        @WebParam(name = "compareDataRequest", targetNamespace = "http://www.ech.ch/xmlns/eCH-0086/1", partName = "body")
        CompareDataRequest body);

}
