
package ch.admin.ws.zas.regcent.upi._0;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ch.ech.xmlns.ech_0084._1.AddEntryToHistoryRequest;
import ch.ech.xmlns.ech_0084._1.EchoLatestResponseRequest;
import ch.ech.xmlns.ech_0084._1.EraseLocalPersonIdRequest;
import ch.ech.xmlns.ech_0084._1.ErasePersonRequest;
import ch.ech.xmlns.ech_0084._1.HeaderType;
import ch.ech.xmlns.ech_0084._1.MergePersonsRequest;
import ch.ech.xmlns.ech_0084._1.NewPersonRequest;
import ch.ech.xmlns.ech_0084._1.Response;
import ch.ech.xmlns.ech_0084._1.UpdateCurrentValuesOrAddEntryToHistoryRequest;
import ch.ech.xmlns.ech_0084._1.UpdateCurrentValuesRequest;
import ch.ech.xmlns.ech_0084._1.UpdateLocalPersonIdRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UPIDeclarationServicePortType", targetNamespace = "http://ws.admin.ch/zas/regcent/UPI/0")
@XmlSeeAlso({
    ch.ech.xmlns.ech_0084._1.ObjectFactory.class,
    ch.ech.xmlns.ech_0071._1.ObjectFactory.class,
    ch.ech.xmlns.ech_0090._1.ObjectFactory.class,
    ch.ech.xmlns.ech_0044._1.ObjectFactory.class,
    ch.ech.xmlns.ech_0011._3.ObjectFactory.class,
    ch.ech.xmlns.ech_0006._2.ObjectFactory.class,
    ch.ech.xmlns.ech_0007._3.ObjectFactory.class,
    ch.ech.xmlns.ech_0008._2.ObjectFactory.class,
    ch.ech.xmlns.ech_0010._3.ObjectFactory.class,
    ch.ech.xmlns.ech_0072._1.ObjectFactory.class
})
public interface UPIDeclarationServicePortType {


    /**
     * 
     * @param body
     * @return
     *     returns ch.ech.xmlns.ech_0084._1.Response
     */
    @WebMethod(action = "http://soap.upi.admin.ch")
    @WebResult(name = "response", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response newPerson(
        @WebParam(name = "newPersonRequest", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", partName = "body")
        NewPersonRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns ch.ech.xmlns.ech_0084._1.Response
     */
    @WebMethod(action = "http://soap.upi.admin.ch")
    @WebResult(name = "response", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response updateLocalPersonId(
        @WebParam(name = "updateLocalPersonIdRequest", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", partName = "body")
        UpdateLocalPersonIdRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns ch.ech.xmlns.ech_0084._1.Response
     */
    @WebMethod(action = "http://soap.upi.admin.ch")
    @WebResult(name = "response", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response updateCurrentValues(
        @WebParam(name = "updateCurrentValuesRequest", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", partName = "body")
        UpdateCurrentValuesRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns ch.ech.xmlns.ech_0084._1.Response
     */
    @WebMethod(action = "http://soap.upi.admin.ch")
    @WebResult(name = "response", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response addEntryToHistory(
        @WebParam(name = "addEntryToHistoryRequest", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", partName = "body")
        AddEntryToHistoryRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns ch.ech.xmlns.ech_0084._1.Response
     */
    @WebMethod(action = "http://soap.upi.admin.ch")
    @WebResult(name = "response", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response updateCurrentValuesOrAddEntryToHistory(
        @WebParam(name = "updateCurrentValuesOrAddEntryToHistoryRequest", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", partName = "body")
        UpdateCurrentValuesOrAddEntryToHistoryRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns ch.ech.xmlns.ech_0084._1.Response
     */
    @WebMethod(action = "http://soap.upi.admin.ch")
    @WebResult(name = "response", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response eraseLocalPersonId(
        @WebParam(name = "eraseLocalPersonIdRequest", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", partName = "body")
        EraseLocalPersonIdRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns ch.ech.xmlns.ech_0084._1.Response
     */
    @WebMethod(action = "http://soap.upi.admin.ch")
    @WebResult(name = "response", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response erasePerson(
        @WebParam(name = "erasePersonRequest", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", partName = "body")
        ErasePersonRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns ch.ech.xmlns.ech_0084._1.Response
     */
    @WebMethod(action = "http://soap.upi.admin.ch")
    @WebResult(name = "response", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response mergePersons(
        @WebParam(name = "mergePersonsRequest", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", partName = "body")
        MergePersonsRequest body);

    /**
     * 
     * @param refused
     * @param person
     * @param header
     * @param accepted
     * @param manualProcessing
     * @param timestamp
     */
    @WebMethod(action = "http://soap.upi.admin.ch")
    @RequestWrapper(localName = "mergePersonOrUpdateLocalPersonIdRequest", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", className = "ch.ech.xmlns.ech_0084._1.MergePersonOrUpdateLocalPersonIdRequest")
    @ResponseWrapper(localName = "response", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", className = "ch.ech.xmlns.ech_0084._1.Response")
    public void mergePersonOrUpdateLocalPersonIdRequest(
        @WebParam(name = "header", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", mode = WebParam.Mode.INOUT)
        Holder<HeaderType> header,
        @WebParam(name = "person", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1")
        List<ch.ech.xmlns.ech_0084._1.MergePersonOrUpdateLocalPersonIdRequest.Person> person,
        @WebParam(name = "timestamp", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", mode = WebParam.Mode.OUT)
        Holder<XMLGregorianCalendar> timestamp,
        @WebParam(name = "accepted", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", mode = WebParam.Mode.OUT)
        Holder<Response.Accepted> accepted,
        @WebParam(name = "manualProcessing", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", mode = WebParam.Mode.OUT)
        Holder<Object> manualProcessing,
        @WebParam(name = "refused", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", mode = WebParam.Mode.OUT)
        Holder<Response.Refused> refused);

    /**
     * 
     * @param body
     * @return
     *     returns ch.ech.xmlns.ech_0084._1.Response
     */
    @WebMethod(action = "http://soap.upi.admin.ch")
    @WebResult(name = "response", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response echoLatestResponse(
        @WebParam(name = "echoLatestResponseRequest", targetNamespace = "http://www.ech.ch/xmlns/eCH-0084/1", partName = "body")
        EchoLatestResponseRequest body);

}
