
package ch.admin.ws.zas.regcent.upi._0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UPIDeclarationService", targetNamespace = "http://ws.admin.ch/zas/regcent/UPI/0", wsdlLocation = "file:/D:/ws/rasc/upi/src/main/wdsl/UPI-declaration.wsdl")
public class UPIDeclarationService
    extends Service
{

    private final static URL UPIDECLARATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException UPIDECLARATIONSERVICE_EXCEPTION;
    private final static QName UPIDECLARATIONSERVICE_QNAME = new QName("http://ws.admin.ch/zas/regcent/UPI/0", "UPIDeclarationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/ws/rasc/upi/src/main/wdsl/UPI-declaration.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UPIDECLARATIONSERVICE_WSDL_LOCATION = url;
        UPIDECLARATIONSERVICE_EXCEPTION = e;
    }

    public UPIDeclarationService() {
        super(__getWsdlLocation(), UPIDECLARATIONSERVICE_QNAME);
    }

    public UPIDeclarationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPIDECLARATIONSERVICE_QNAME, features);
    }

    public UPIDeclarationService(URL wsdlLocation) {
        super(wsdlLocation, UPIDECLARATIONSERVICE_QNAME);
    }

    public UPIDeclarationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPIDECLARATIONSERVICE_QNAME, features);
    }

    public UPIDeclarationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UPIDeclarationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UPIDeclarationServicePortType
     */
    @WebEndpoint(name = "UPIDeclarationServicePort")
    public UPIDeclarationServicePortType getUPIDeclarationServicePort() {
        return super.getPort(new QName("http://ws.admin.ch/zas/regcent/UPI/0", "UPIDeclarationServicePort"), UPIDeclarationServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UPIDeclarationServicePortType
     */
    @WebEndpoint(name = "UPIDeclarationServicePort")
    public UPIDeclarationServicePortType getUPIDeclarationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.admin.ch/zas/regcent/UPI/0", "UPIDeclarationServicePort"), UPIDeclarationServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UPIDECLARATIONSERVICE_EXCEPTION!= null) {
            throw UPIDECLARATIONSERVICE_EXCEPTION;
        }
        return UPIDECLARATIONSERVICE_WSDL_LOCATION;
    }

}
