
package ch.admin.ws.zas.regcent.upi._0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UPIFileTransferService", targetNamespace = "http://ws.admin.ch/zas/regcent/UPI/0", wsdlLocation = "file:/D:/ws/rasc/upi/src/main/wdsl/UPI-FileTransfer.wsdl")
public class UPIFileTransferService
    extends Service
{

    private final static URL UPIFILETRANSFERSERVICE_WSDL_LOCATION;
    private final static WebServiceException UPIFILETRANSFERSERVICE_EXCEPTION;
    private final static QName UPIFILETRANSFERSERVICE_QNAME = new QName("http://ws.admin.ch/zas/regcent/UPI/0", "UPIFileTransferService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/ws/rasc/upi/src/main/wdsl/UPI-FileTransfer.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UPIFILETRANSFERSERVICE_WSDL_LOCATION = url;
        UPIFILETRANSFERSERVICE_EXCEPTION = e;
    }

    public UPIFileTransferService() {
        super(__getWsdlLocation(), UPIFILETRANSFERSERVICE_QNAME);
    }

    public UPIFileTransferService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPIFILETRANSFERSERVICE_QNAME, features);
    }

    public UPIFileTransferService(URL wsdlLocation) {
        super(wsdlLocation, UPIFILETRANSFERSERVICE_QNAME);
    }

    public UPIFileTransferService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPIFILETRANSFERSERVICE_QNAME, features);
    }

    public UPIFileTransferService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UPIFileTransferService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UPIFileTransferPortType
     */
    @WebEndpoint(name = "UPIFileTransferServicePort")
    public UPIFileTransferPortType getUPIFileTransferServicePort() {
        return super.getPort(new QName("http://ws.admin.ch/zas/regcent/UPI/0", "UPIFileTransferServicePort"), UPIFileTransferPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UPIFileTransferPortType
     */
    @WebEndpoint(name = "UPIFileTransferServicePort")
    public UPIFileTransferPortType getUPIFileTransferServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.admin.ch/zas/regcent/UPI/0", "UPIFileTransferServicePort"), UPIFileTransferPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UPIFILETRANSFERSERVICE_EXCEPTION!= null) {
            throw UPIFILETRANSFERSERVICE_EXCEPTION;
        }
        return UPIFILETRANSFERSERVICE_WSDL_LOCATION;
    }

}
