// Bank.idl

module Bank
{
  exception BankException
  { string reason;
  };

  interface DebitCredit
  {
    void debitCreditTransaction(in double random1,
                                in double random2,
                                in boolean staticTxn)
                 raises (BankException);
  };

  interface Dispenser
  {
    DebitCredit reserveDebitCreditObject() raises (BankException);
    void        releaseDebitCreditObject(in DebitCredit debitCreditObject)
                            raises (BankException);
  };

};