info:
  app.name: "@project.name@"
  app.description: "@project.description@"
  app.version: "@project.version@"
  build.artifact: "@project.artifactId@"
  build.time: "@build.timestamp@"

app:
  url: http://localhost:8080
  rememberme-cookie-key: golb
  rememberme-cookie-valid-in-days: 31
  default-email-sender: no-reply@golb.com
  login-lock-attempts: 10
  login-lock-minutes: 30

mongodb:
  uri: mongodb://localhost/golbp?w=1&wtimeoutMS=0&journal=true

spring:
  jackson:
    serialization:
      write-date-timestamps-as-nanoseconds: false
  
  resources:
    cache-period: 31556926
  
  mvc:
    favicon:
      enabled: false

  mail:
    host: localhost    

  async:
    core-pool-size: 2
    max-pool-size: 20
    queue-capacity: 200
    thread-name-prefix: starter-async-executor

  main:
    banner-mode: log 


server:
  port: 80
  session:
    timeout: 480
  compression:
     enabled: false
     mime-types: text/html,text/xml,text/plain,text/css,application/json,application/javascript,image/svg+xml,application/x-font-ttf,application/x-font-truetype,application/x-font-opentype,application/vnd.ms-fontobject,application/font-sfnt     
  use-forward-headers: true

logging:
  level:
    org.springframework: WARN
    org.mongodb: WARN
    org.apache: WARN
    ch: WARN
  file: ./app.log
