spring:
  resources:
    cache-period: 0
    static-locations: file:./client/,file:./client/ext/classic/locale/overrides/de/


server:
  port: 8080
  compression:
    enabled: false

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework: INFO
    org.apache: INFO
    ch: INFO
