/**
 * Generated by Gas3 v1.0.0 (Granite Data Services) on Fri Jan 11 04:50:44 CET 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package ch.ess.issue.entity {

    [Bindable]
    [RemoteClass(alias="ch.ess.issue.entity.Project")]
    public class Project extends ProjectBase {
    }
}