/**
 * Generated by Gas3 v1.0.0 (Granite Data Services) on Fri Jan 11 13:24:23 CET 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT WILL BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (User.as).
 */

package ch.ess.issue.entity {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class UserBase extends AbstractEntity {

        private var _email:String;
        private var _enabled:Boolean;
        private var _firstName:String;
        private var _lastName:String;
        private var _password:String;
        private var _rememberMeToken:String;
        private var _role:String;
        private var _username:String;

        public function set email(value:String):void {
            _email = value;
        }
        public function get email():String {
            return _email;
        }

        public function set enabled(value:Boolean):void {
            _enabled = value;
        }
        public function get enabled():Boolean {
            return _enabled;
        }

        public function set firstName(value:String):void {
            _firstName = value;
        }
        public function get firstName():String {
            return _firstName;
        }

        public function set lastName(value:String):void {
            _lastName = value;
        }
        public function get lastName():String {
            return _lastName;
        }

        public function set password(value:String):void {
            _password = value;
        }
        public function get password():String {
            return _password;
        }

        public function set rememberMeToken(value:String):void {
            _rememberMeToken = value;
        }
        public function get rememberMeToken():String {
            return _rememberMeToken;
        }

        public function set role(value:String):void {
            _role = value;
        }
        public function get role():String {
            return _role;
        }

        public function set username(value:String):void {
            _username = value;
        }
        public function get username():String {
            return _username;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            if (meta::isInitialized()) {
                _email = input.readObject() as String;
                _enabled = input.readObject() as Boolean;
                _firstName = input.readObject() as String;
                _lastName = input.readObject() as String;
                _password = input.readObject() as String;
                _rememberMeToken = input.readObject() as String;
                _role = input.readObject() as String;
                _username = input.readObject() as String;
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            if (meta::isInitialized()) {
                output.writeObject(_email);
                output.writeObject(_enabled);
                output.writeObject(_firstName);
                output.writeObject(_lastName);
                output.writeObject(_password);
                output.writeObject(_rememberMeToken);
                output.writeObject(_role);
                output.writeObject(_username);
            }
        }
    }
}