/*
 * This file is generated by jOOQ.
 */
package ch.rasc.travellog.db;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ch.rasc.travellog.db.tables.AppSession;
import ch.rasc.travellog.db.tables.AppUser;
import ch.rasc.travellog.db.tables.Log;
import ch.rasc.travellog.db.tables.LogPhoto;
import ch.rasc.travellog.db.tables.Travel;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>DEFAULT_SCHEMA</code>
	 */
	public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

	/**
	 * The table <code>app_session</code>.
	 */
	public final AppSession APP_SESSION = AppSession.APP_SESSION;

	/**
	 * The table <code>app_user</code>.
	 */
	public final AppUser APP_USER = AppUser.APP_USER;

	/**
	 * The table <code>log</code>.
	 */
	public final Log LOG = Log.LOG;

	/**
	 * The table <code>log_photo</code>.
	 */
	public final LogPhoto LOG_PHOTO = LogPhoto.LOG_PHOTO;

	/**
	 * The table <code>travel</code>.
	 */
	public final Travel TRAVEL = Travel.TRAVEL;

	/**
	 * No further instances allowed
	 */
	private DefaultSchema() {
		super("", null);
	}

	@Override
	public Catalog getCatalog() {
		return DefaultCatalog.DEFAULT_CATALOG;
	}

	@Override
	public final List<Table<?>> getTables() {
		return Arrays.asList(AppSession.APP_SESSION, AppUser.APP_USER, Log.LOG,
				LogPhoto.LOG_PHOTO, Travel.TRAVEL);
	}
}
