package gtf.ss.common;	

public final class SQLStatements {

	public static final String LC_SELECT_SQL_STR = 
			"SELECT GTFLC.DOSSIER.DOSSIER_NUMBER, GTFLC.DOSSIER.BRANCH, "+
			"GTFLC.DOSSIER.BRANCH_GROUP,"+
			"GTFLC.LEGAL_ENTITY.NAME, "+
			"GTFLC.LEGAL_ENTITY.CITY, GTFLC.PARTICIPANT.REFERENCE_NUMBER "+
			"FROM GTFLC.DOSSIER, GTFLC.PARTICIPANT, GTFLC.LEGAL_ENTITY "+
			"WHERE GTFLC.DOSSIER.OID = GTFLC.PARTICIPANT.DOSSIER_OID AND "+
			"GTFLC.PARTICIPANT.LE_OID = GTFLC.LEGAL_ENTITY.OID "+
			"AND GTFLC.LEGAL_ENTITY.CATEGORY='FI'  "+
			"AND GTFLC.DOSSIER.UPDATE_TS > ? "+
			"GROUP BY GTFLC.DOSSIER.DOSSIER_NUMBER, GTFLC.DOSSIER.BRANCH, GTFLC.DOSSIER.BRANCH_GROUP, GTFLC.LEGAL_ENTITY.NAME, "+
			"GTFLC.LEGAL_ENTITY.CITY, GTFLC.PARTICIPANT.REFERENCE_NUMBER";


	public static final String DC_SELECT_SQL_STR = 
			"SELECT GTFLC.DC_DOSSIER.DOSSIER_NUMBER, GTFLC.DC_DOSSIER.BRANCH, "+
			"GTFLC.DC_DOSSIER.BRANCH_GROUP,"+
			"GTFLC.LEGAL_ENTITY.NAME, "+
			"GTFLC.LEGAL_ENTITY.CITY, GTFLC.DC_PARTICIPANT.REFERENCE_NUMBER "+
			"FROM GTFLC.DC_DOSSIER, GTFLC.DC_PARTICIPANT, GTFLC.LEGAL_ENTITY "+
			"WHERE GTFLC.DC_DOSSIER.OID = GTFLC.DC_PARTICIPANT.DOSSIER_OID AND "+
			"GTFLC.DC_PARTICIPANT.LE_OID = GTFLC.LEGAL_ENTITY.OID "+
			"AND GTFLC.LEGAL_ENTITY.CATEGORY='FI'  "+
			"AND GTFLC.DC_DOSSIER.UPDATE_TS > ? "+
			"GROUP BY GTFLC.DC_DOSSIER.DOSSIER_NUMBER, GTFLC.DC_DOSSIER.BRANCH, GTFLC.DC_DOSSIER.BRANCH_GROUP, GTFLC.LEGAL_ENTITY.NAME, "+
			"GTFLC.LEGAL_ENTITY.CITY, GTFLC.DC_PARTICIPANT.REFERENCE_NUMBER";
			
	public static final String RC_SELECT_SQL_STR = 
			"SELECT GTFLC.RC_DOSSIER.DOSSIER_NUMBER, GTFLC.RC_DOSSIER.BRANCH, "+
			"GTFLC.RC_DOSSIER.BRANCH_GROUP,"+
			"GTFLC.LEGAL_ENTITY.NAME, "+
			"GTFLC.LEGAL_ENTITY.CITY, GTFLC.RC_PARTICIPANT.REFERENCE_NUMBER "+
			"FROM GTFLC.RC_DOSSIER, GTFLC.RC_PARTICIPANT, GTFLC.LEGAL_ENTITY "+
			"WHERE GTFLC.RC_DOSSIER.OID = GTFLC.RC_PARTICIPANT.DOSSIER_OID AND "+
			"GTFLC.RC_PARTICIPANT.LE_OID = GTFLC.LEGAL_ENTITY.OID "+
			"AND GTFLC.LEGAL_ENTITY.CATEGORY='FI'  "+
			"AND GTFLC.RC_DOSSIER.UPDATE_TS > ? "+
			"GROUP BY GTFLC.RC_DOSSIER.DOSSIER_NUMBER, GTFLC.RC_DOSSIER.BRANCH, GTFLC.RC_DOSSIER.BRANCH_GROUP, GTFLC.LEGAL_ENTITY.NAME, "+ 
			"GTFLC.LEGAL_ENTITY.CITY, GTFLC.RC_PARTICIPANT.REFERENCE_NUMBER";

	public static final String LOI_SELECT_SQL_STR =			
			"SELECT GTFLC.LOI_DOSSIER.DOSSIER_NUMBER, GTFLC.LOI_DOSSIER.BRANCH, "+
			"GTFLC.LOI_DOSSIER.BRANCH_GROUP,"+
			"GTFLC.LEGAL_ENTITY.NAME, "+
			"GTFLC.LEGAL_ENTITY.CITY, GTFLC.LOI_PARTICIPANT.REFERENCE_NUMBER "+
			"FROM GTFLC.LOI_DOSSIER, GTFLC.LOI_PARTICIPANT, GTFLC.LEGAL_ENTITY "+
			"WHERE GTFLC.LOI_DOSSIER.OID = GTFLC.LOI_PARTICIPANT.DOSSIER_OID AND "+
			"GTFLC.LOI_PARTICIPANT.LE_OID = GTFLC.LEGAL_ENTITY.OID "+
			"AND GTFLC.LEGAL_ENTITY.CATEGORY='FI'  "+
			"AND GTFLC.LOI_DOSSIER.UPDATE_TS > ? "+
			"GROUP BY GTFLC.LOI_DOSSIER.DOSSIER_NUMBER, GTFLC.LOI_DOSSIER.BRANCH, GTFLC.LOI_DOSSIER.BRANCH_GROUP, GTFLC.LEGAL_ENTITY.NAME, "+
			"GTFLC.LEGAL_ENTITY.CITY, GTFLC.LOI_PARTICIPANT.REFERENCE_NUMBER";

	public static final String SELECT_DIGITS_AFTER = 
			"select gtflc.currency.iso_code_alpha, gtflc.currency1.iso_code_numeric, digits_after from gtflc.currency, gtflc.currency1 " +
			"where gtflc.currency.iso_code_alpha = gtflc.currency1.iso_code_alpha ";
			

	public static final String SELECT_DC_AMOUNT_STR = 
					"select GTFLC.DC_DOSSIER.DOSSIER_NUMBER, collection_amount from gtflc.dc_dossier, "+
					"gtflc.collect_order where "+
					"gtflc.dc_dossier.oid = gtflc.collect_order.dossier_oid "+
					"AND GTFLC.DC_DOSSIER.UPDATE_TS > ? ";
					
	public static final String SELECT_LOI_AMOUNT_STR = 
					"select GTFLC.LOI_DOSSIER.DOSSIER_NUMBER, amount from gtflc.loi_dossier, "+
 					"gtflc.loi_issuance where "+ 
					"gtflc.loi_dossier.oid = gtflc.loi_issuance.dossier_oid "+
					"AND GTFLC.LOI_DOSSIER.UPDATE_TS > ? ";
			
	public static final String SELECT_RC_AMOUNT_STR = 					
					"SELECT GTFLC.RC_DOSSIER.DOSSIER_NUMBER, "+
					"GTFLC.RC_AMOUNT.VALUE, "+
					"GTFLC.RC_AMT_SPEC.POS_TOLERANCE "+
					"FROM GTFLC.RC_DOSSIER, GTFLC.RC_REIMBURS_AUTH, GTFLC.RC_AMOUNT,"+
					"GTFLC.RC_AMT_SPEC "+
					"WHERE "+
					"GTFLC.RC_DOSSIER.OID = GTFLC.RC_REIMBURS_AUTH.DOSSIER_OID AND "+
					"GTFLC.RC_REIMBURS_AUTH.OID = GTFLC.RC_AMOUNT.PARENTOID AND "+
					"GTFLC.RC_AMOUNT.OID = GTFLC.RC_AMT_SPEC.PARENT_OID " +
					"AND GTFLC.RC_DOSSIER.UPDATE_TS > ? ";
	
	public static final String SELECT_LC_AMOUNT_STR1 = 
					"SELECT GTFLC.DOSSIER.DOSSIER_NUMBER, GTFLC.LC_AMOUNT.AMOUNT1 "+
					"FROM GTFLC.DOSSIER, GTFLC.DEF_DOSSIER_ITEM, GTFLC.LC_AMOUNT "+
					"WHERE GTFLC.LC_AMOUNT.SPEC_TYPE IN ('EX', 'PL', 'UT') "+
					"AND gtflc.def_dossier_item.dossier_oid = gtflc.dossier.oid  "+
					"AND gtflc.def_dossier_item.oid = gtflc.lc_amount.dossier_item_oid "+
					"AND GTFLC.DOSSIER.UPDATE_TS > ? "+
					"UNION "+
					"SELECT GTFLC.DOSSIER.DOSSIER_NUMBER, GTFLC.LC_AMOUNT.AMOUNT2 "+
					"FROM GTFLC.DOSSIER, GTFLC.DEF_DOSSIER_ITEM, GTFLC.LC_AMOUNT "+
					"WHERE GTFLC.LC_AMOUNT.SPEC_TYPE = 'MM' "+
					"AND gtflc.def_dossier_item.dossier_oid = gtflc.dossier.oid  "+
					"AND gtflc.def_dossier_item.oid = gtflc.lc_amount.dossier_item_oid "+
					"AND GTFLC.DOSSIER.UPDATE_TS > ? ";
					
	public static final String SELECT_LC_AMOUNT_STR2 = 
					"SELECT GTFLC.DOSSIER.DOSSIER_NUMBER, GTFLC.LC_AMOUNT.AMOUNT1 "+
					"FROM GTFLC.DOSSIER, GTFLC.DEF_DOSSIER_ITEM, GTFLC.LC_AMOUNT "+
					"WHERE GTFLC.LC_AMOUNT.SPEC_TYPE = 'AB' "+
					"AND gtflc.def_dossier_item.dossier_oid = gtflc.dossier.oid  "+
					"AND gtflc.def_dossier_item.oid = gtflc.lc_amount.dossier_item_oid "+
					"AND GTFLC.DOSSIER.UPDATE_TS > ? ";

	public static final String SELECT_LC_AMOUNT_STR3 = 					
					"SELECT GTFLC.DOSSIER.DOSSIER_NUMBER, GTFLC.LC_AMOUNT.AMOUNT1, GTFLC.LC_AMOUNT.POSITIVE_TOLERANCE "+
					"FROM GTFLC.DOSSIER, GTFLC.DEF_DOSSIER_ITEM, GTFLC.LC_AMOUNT "+
					"WHERE GTFLC.LC_AMOUNT.SPEC_TYPE = 'TL' "+
					"AND gtflc.def_dossier_item.dossier_oid = gtflc.dossier.oid "+
					"AND gtflc.def_dossier_item.oid = gtflc.lc_amount.dossier_item_oid "+
					"AND GTFLC.DOSSIER.UPDATE_TS > ? ";
}
			
			
				