/**
 * Class ContingentLiability.java - for table <contingent_liability> 
 * 
 * THIS PROGRAM IS PROVIDED AS-IS WITHOUT WARRANTY OF ANY KIND. 
 * 2LINK CONSULTING, INC. DISCLAIMS ALL WARRANTIES EXPRESSED 
 * OR IMPLIED FOR THIS PROGRAM. 2LINK SHALL NOT BE LIABLE FOR 
 * ANY OUTCOMES CAUSED BY THE USE OR MISUSE OF THIS PRODUCT. 
 * YOU MAY FREELY USE AND DISTRIBUTE THE GENERATED JAVA SOURCE 
 * FROM THIS PROGRAM ROYALTY FREE. 
 * 
 * Generated by: DbGen Professional Edition Version 1.0b2 
 * Generated on: 4/18/98 9:50 PM 
 * 
 * Please visit our web site at http://www.2link.net/dbgen/. 
 */

import java.sql.*;
import java.util.*;
import java.net.*;
import java.io.*;
import com.twolink.dbgen.support.*;

public class ContingentLiability implements java.io.Serializable, com.twolink.dbgen.support.Data
{
	/*
	 * Table Fields 	
	 */
	private int _sequence_number;
	private String _type;
	private int _gtf_number;
	private String _currency;
	private double _amount;
	private String _acct_mgmt_unit;
	private String _account_number;
	private java.sql.Date _expiry_date;
	private double _exchange_rate;
	private String _gtf_proc_center;
	private String _customer_ref;
	private String _gtf_type;
	private String _dossier_item;
	private String _bu_code;
	protected transient java.beans.PropertyChangeSupport propertyChange = new java.beans.PropertyChangeSupport(this);
	
	/**
	 * Default Constructor 	
	 */
	public ContingentLiability()
	{
	}
	
	/**
	 * Key Constructor 	
	 */
	public ContingentLiability(int _gtf_number, String _gtf_proc_center)
	{
		this._gtf_number = _gtf_number;
		this._gtf_proc_center = _gtf_proc_center;
	}
	
	/**
	 * Normal Constructor 	
	 */
	public ContingentLiability(int _sequence_number, String _type, int _gtf_number, String _currency, double _amount, String _acct_mgmt_unit, String _account_number, java.sql.Date _expiry_date, double _exchange_rate, String _gtf_proc_center, String _customer_ref, String _gtf_type, String _dossier_item, String _bu_code)
	{
		this._sequence_number = _sequence_number;
		this._type = _type;
		this._gtf_number = _gtf_number;
		this._currency = _currency;
		this._amount = _amount;
		this._acct_mgmt_unit = _acct_mgmt_unit;
		this._account_number = _account_number;
		this._expiry_date = _expiry_date;
		this._exchange_rate = _exchange_rate;
		this._gtf_proc_center = _gtf_proc_center;
		this._customer_ref = _customer_ref;
		this._gtf_type = _gtf_type;
		this._dossier_item = _dossier_item;
		this._bu_code = _bu_code;
	}

    public boolean equals(Object obj)
    {
	    if (obj instanceof ContingentLiability)
	    {	
	        ContingentLiability cl = (ContingentLiability)obj;
	        
    	    return ( getType().equals(cl.getType()) && (getGtf_number() == cl.getGtf_number()) &&
    	             getCurrency().equals(cl.getCurrency()) && (getAmount() == cl.getAmount()) &&
    	             getAcct_mgmt_unit().equals(cl.getAcct_mgmt_unit()) && 
    	             getAccount_number().equals(cl.getAccount_number()) &&
    	             getExpiry_date().equals(cl.getExpiry_date()) &&
    	             getGtf_proc_center().equals(cl.getGtf_proc_center()) );
	    }
    	return false;
    }

	/**
	 * Get the sequence_number property (int) value. 	
	 */
	public int getSequence_number()
	{
		return _sequence_number;
	}

	/**
	 * Set the sequence_number property (int) value. 	
	 */
	public void setSequence_number(int _sequence_number)
	{
		/* Get the old property value for fire property change event. */
		int oldValue = _sequence_number;
		/* Set the sequence_number property (attribute) to the new value. */
		this._sequence_number = _sequence_number;
		/* Fire (signal/notify) the sequence_number property change event. */
		firePropertyChange("sequence_number", new Integer(oldValue), new Integer(_sequence_number));
	}

	/**
	 * Get the type property (String) value. 	
	 */
	public String getType()
	{
		return _type;
	}

	/**
	 * Set the type property (String) value. 	
	 */
	public void setType(String _type)
	{
		/* Get the old property value for fire property change event. */
		String oldValue = _type;
		/* Set the type property (attribute) to the new value. */
		this._type = _type;
		/* Fire (signal/notify) the type property change event. */
		firePropertyChange("type", oldValue, _type);
	}

	/**
	 * Get the gtf_number property (int) value. 	
	 */
	public int getGtf_number()
	{
		return _gtf_number;
	}

	/**
	 * Set the gtf_number property (int) value. 	
	 */
	public void setGtf_number(int _gtf_number)
	{
		/* Get the old property value for fire property change event. */
		int oldValue = _gtf_number;
		/* Set the gtf_number property (attribute) to the new value. */
		this._gtf_number = _gtf_number;
		/* Fire (signal/notify) the gtf_number property change event. */
		firePropertyChange("gtf_number", new Integer(oldValue), new Integer(_gtf_number));
	}

	/**
	 * Get the currency property (String) value. 	
	 */
	public String getCurrency()
	{
		return _currency;
	}

	/**
	 * Set the currency property (String) value. 	
	 */
	public void setCurrency(String _currency)
	{
		/* Get the old property value for fire property change event. */
		String oldValue = _currency;
		/* Set the currency property (attribute) to the new value. */
		this._currency = _currency;
		/* Fire (signal/notify) the currency property change event. */
		firePropertyChange("currency", oldValue, _currency);
	}

	/**
	 * Get the amount property (double) value. 	
	 */
	public double getAmount()
	{
		return _amount;
	}

	/**
	 * Set the amount property (double) value. 	
	 */
	public void setAmount(double _amount)
	{
		/* Get the old property value for fire property change event. */
		double oldValue = _amount;
		/* Set the amount property (attribute) to the new value. */
		this._amount = _amount;
		/* Fire (signal/notify) the amount property change event. */
		firePropertyChange("amount", new Double(oldValue), new Double(_amount));
	}

	/**
	 * Get the acct_mgmt_unit property (String) value. 	
	 */
	public String getAcct_mgmt_unit()
	{
		return _acct_mgmt_unit;
	}

	/**
	 * Set the acct_mgmt_unit property (String) value. 	
	 */
	public void setAcct_mgmt_unit(String _acct_mgmt_unit)
	{
		/* Get the old property value for fire property change event. */
		String oldValue = _acct_mgmt_unit;
		/* Set the acct_mgmt_unit property (attribute) to the new value. */
		this._acct_mgmt_unit = _acct_mgmt_unit;
		/* Fire (signal/notify) the acct_mgmt_unit property change event. */
		firePropertyChange("acct_mgmt_unit", oldValue, _acct_mgmt_unit);
	}

	/**
	 * Get the account_number property (String) value. 	
	 */
	public String getAccount_number()
	{
		return _account_number;
	}

	/**
	 * Set the account_number property (String) value. 	
	 */
	public void setAccount_number(String _account_number)
	{
		/* Get the old property value for fire property change event. */
		String oldValue = _account_number;
		/* Set the account_number property (attribute) to the new value. */
		this._account_number = _account_number;
		/* Fire (signal/notify) the account_number property change event. */
		firePropertyChange("account_number", oldValue, _account_number);
	}

	/**
	 * Get the expiry_date property (java.sql.Date) value. 	
	 */
	public java.sql.Date getExpiry_date()
	{
		return _expiry_date;
	}

	/**
	 * Set the expiry_date property (java.sql.Date) value. 	
	 */
	public void setExpiry_date(java.sql.Date _expiry_date)
	{
		/* Get the old property value for fire property change event. */
		java.sql.Date oldValue = _expiry_date;
		/* Set the expiry_date property (attribute) to the new value. */
		this._expiry_date = _expiry_date;
		/* Fire (signal/notify) the expiry_date property change event. */
		firePropertyChange("expiry_date", oldValue, _expiry_date);
	}

	/**
	 * Get the exchange_rate property (double) value. 	
	 */
	public double getExchange_rate()
	{
		return _exchange_rate;
	}

	/**
	 * Set the exchange_rate property (double) value. 	
	 */
	public void setExchange_rate(double _exchange_rate)
	{
		/* Get the old property value for fire property change event. */
		double oldValue = _exchange_rate;
		/* Set the exchange_rate property (attribute) to the new value. */
		this._exchange_rate = _exchange_rate;
		/* Fire (signal/notify) the exchange_rate property change event. */
		firePropertyChange("exchange_rate", new Double(oldValue), new Double(_exchange_rate));
	}

	/**
	 * Get the gtf_proc_center property (String) value. 	
	 */
	public String getGtf_proc_center()
	{
		return _gtf_proc_center;
	}

	/**
	 * Set the gtf_proc_center property (String) value. 	
	 */
	public void setGtf_proc_center(String _gtf_proc_center)
	{
		/* Get the old property value for fire property change event. */
		String oldValue = _gtf_proc_center;
		/* Set the gtf_proc_center property (attribute) to the new value. */
		this._gtf_proc_center = _gtf_proc_center;
		/* Fire (signal/notify) the gtf_proc_center property change event. */
		firePropertyChange("gtf_proc_center", oldValue, _gtf_proc_center);
	}

	/**
	 * Get the customer_ref property (String) value. 	
	 */
	public String getCustomer_ref()
	{
		return _customer_ref;
	}

	/**
	 * Set the customer_ref property (String) value. 	
	 */
	public void setCustomer_ref(String _customer_ref)
	{
		/* Get the old property value for fire property change event. */
		String oldValue = _customer_ref;
		/* Set the customer_ref property (attribute) to the new value. */
		this._customer_ref = _customer_ref;
		/* Fire (signal/notify) the customer_ref property change event. */
		firePropertyChange("customer_ref", oldValue, _customer_ref);
	}

	/**
	 * Get the gtf_type property (String) value. 	
	 */
	public String getGtf_type()
	{
		return _gtf_type;
	}

	/**
	 * Set the gtf_type property (String) value. 	
	 */
	public void setGtf_type(String _gtf_type)
	{
		/* Get the old property value for fire property change event. */
		String oldValue = _gtf_type;
		/* Set the gtf_type property (attribute) to the new value. */
		this._gtf_type = _gtf_type;
		/* Fire (signal/notify) the gtf_type property change event. */
		firePropertyChange("gtf_type", oldValue, _gtf_type);
	}

	/**
	 * Get the dossier_item property (String) value. 	
	 */
	public String getDossier_item()
	{
		return _dossier_item;
	}

	/**
	 * Set the dossier_item property (String) value. 	
	 */
	public void setDossier_item(String _dossier_item)
	{
		/* Get the old property value for fire property change event. */
		String oldValue = _dossier_item;
		/* Set the dossier_item property (attribute) to the new value. */
		this._dossier_item = _dossier_item;
		/* Fire (signal/notify) the dossier_item property change event. */
		firePropertyChange("dossier_item", oldValue, _dossier_item);
	}

	/**
	 * Get the bu_code property (String) value. 	
	 */
	public String getBu_code()
	{
		return _bu_code;
	}

	/**
	 * Set the bu_code property (String) value. 	
	 */
	public void setBu_code(String _bu_code)
	{
		/* Get the old property value for fire property change event. */
		String oldValue = _bu_code;
		/* Set the bu_code property (attribute) to the new value. */
		this._bu_code = _bu_code;
		/* Fire (signal/notify) the bu_code property change event. */
		firePropertyChange("bu_code", oldValue, _bu_code);
	}

	/**
	 * Add a property change listener 	
	 */
	public synchronized void addPropertyChangeListener(java.beans.PropertyChangeListener listener)
	{
		if (propertyChange == null)
			propertyChange = new java.beans.PropertyChangeSupport(this);
		propertyChange.addPropertyChangeListener(listener);
	}

	/**
	 * Remove a property change listener 	
	 */
	public synchronized void removePropertyChangeListener(java.beans.PropertyChangeListener listener)
	{
		if (propertyChange == null)
			propertyChange = new java.beans.PropertyChangeSupport(this);
		propertyChange.removePropertyChangeListener(listener);
	}

	/**
	 * Fire a property change event. 	
	 */
	public void firePropertyChange(String propertyName, Object oldValue, Object newValue)
	{
		if (propertyChange == null)
			propertyChange = new java.beans.PropertyChangeSupport(this);
		propertyChange.firePropertyChange(propertyName, oldValue, newValue);
	}

	/**
	 * Clear the ContingentLiability object. 	
	 */
	public void clear()
	{
		_sequence_number = 0;
		_type = null;
		_gtf_number = 0;
		_currency = null;
		_amount = 0;
		_acct_mgmt_unit = null;
		_account_number = null;
		_expiry_date = null;
		_exchange_rate = 0;
		_gtf_proc_center = null;
		_customer_ref = null;
		_gtf_type = null;
		_dossier_item = null;
		_bu_code = null;
	}

	/**
	 * Return a printable representation of the ContingentLiability 
	 * object. 	
	 */
	public String toString()
	{
		return "#(" + _sequence_number + " " + _type + " " + _gtf_number + " " + _currency + " " + _amount + " " + _acct_mgmt_unit + " " + _account_number + " " + _expiry_date + " " + _exchange_rate + " " + _gtf_proc_center + " " + _customer_ref + " " + _gtf_type + " " + _dossier_item + " " + _bu_code + ")";
	}
	
	public String toExternalString() {
	    return (_sequence_number + "\t" + _type + "\t" + _gtf_number+ "\t" + _currency + "\t" + 
	            _amount + "\t" + _acct_mgmt_unit+ "\t" + _account_number + "\t" + _expiry_date + 
	            "\t" + _exchange_rate + "\t" + _gtf_proc_center + "\t" + _customer_ref + "\t" + 
	            _gtf_type + "\t" + _dossier_item + "\t" + _bu_code);
	}
	

	/**
	 * Get the table name. 	
	 */
	public String getTableName()
	{
		return "contingent_liability";
	}

	/**
	 * Get the SQL condition for key fields. 	
	 */
	public String getKeyConditions()
	{
		return "gtf_number = " + _gtf_number + " AND " + "gtf_proc_center = " + "'" + com.twolink.dbgen.support.StringHelper.escape(_gtf_proc_center) + "'";
	}

	/**
	 * Get the INSERT values clause. 	
	 */
	public String getInsertValues()
	{
		return _sequence_number + "," + "'" + com.twolink.dbgen.support.StringHelper.escape(_type) + "'" + "," + _gtf_number + "," + "'" + com.twolink.dbgen.support.StringHelper.escape(_currency) + "'" + "," + _amount + "," + "'" + com.twolink.dbgen.support.StringHelper.escape(_acct_mgmt_unit) + "'" + "," + "'" + com.twolink.dbgen.support.StringHelper.escape(_account_number) + "'" + "," + "'" + _expiry_date + "'" + "," + _exchange_rate + "," + "'" + com.twolink.dbgen.support.StringHelper.escape(_gtf_proc_center) + "'" + "," + "'" + com.twolink.dbgen.support.StringHelper.escape(_customer_ref) + "'" + "," + "'" + com.twolink.dbgen.support.StringHelper.escape(_gtf_type) + "'" + "," + "'" + com.twolink.dbgen.support.StringHelper.escape(_dossier_item) + "'" + "," + "'" + com.twolink.dbgen.support.StringHelper.escape(_bu_code) + "'";
	}

	/**
	 * Get the UPDATE set clause. 	
	 */
	public String getUpdateValues()
	{
		return "sequence_number" + " = " + _sequence_number + "," + "type" + " = " + "'" + com.twolink.dbgen.support.StringHelper.escape(_type) + "'" + "," + "gtf_number" + " = " + _gtf_number + "," + "currency" + " = " + "'" + com.twolink.dbgen.support.StringHelper.escape(_currency) + "'" + "," + "amount" + " = " + _amount + "," + "acct_mgmt_unit" + " = " + "'" + com.twolink.dbgen.support.StringHelper.escape(_acct_mgmt_unit) + "'" + "," + "account_number" + " = " + "'" + com.twolink.dbgen.support.StringHelper.escape(_account_number) + "'" + "," + "expiry_date" + " = " + "'" + _expiry_date + "'" + "," + "exchange_rate" + " = " + _exchange_rate + "," + "gtf_proc_center" + " = " + "'" + com.twolink.dbgen.support.StringHelper.escape(_gtf_proc_center) + "'" + "," + "customer_ref" + " = " + "'" + com.twolink.dbgen.support.StringHelper.escape(_customer_ref) + "'" + "," + "gtf_type" + " = " + "'" + com.twolink.dbgen.support.StringHelper.escape(_gtf_type) + "'" + "," + "dossier_item" + " = " + "'" + com.twolink.dbgen.support.StringHelper.escape(_dossier_item) + "'" + "," + "bu_code" + " = " + "'" + com.twolink.dbgen.support.StringHelper.escape(_bu_code) + "'";
	}

	/**
	 * Make a new ContingentLiability object. 	
	 */
	public com.twolink.dbgen.support.Data makeObject(ResultSet rs)
	  throws SQLException
	{
		return new ContingentLiability(rs.getInt(1), rs.getString(2), rs.getInt(3), rs.getString(4), rs.getDouble(5), rs.getString(6), rs.getString(7), rs.getDate(8), rs.getDouble(9), rs.getString(10), rs.getString(11), rs.getString(12), rs.getString(13), rs.getString(14));
	}

	/**
	 * Set the key fields from a parent class. 	
	 */
	public void setKeysFromParent(com.twolink.dbgen.support.Data parent)
	{
	}
}
