/*
 * This file is generated by jOOQ.
 */
package ch.rasc.travellog.db.tables.records;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import ch.rasc.travellog.db.tables.Travel;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TravelRecord extends UpdatableRecordImpl<TravelRecord>
		implements Record4<Long, String, Long, LocalDateTime> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>travel.id</code>.
	 */
	public void setId(Long value) {
		set(0, value);
	}

	/**
	 * Getter for <code>travel.id</code>.
	 */
	public Long getId() {
		return (Long) get(0);
	}

	/**
	 * Setter for <code>travel.name</code>.
	 */
	public void setName(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>travel.name</code>.
	 */
	public String getName() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>travel.app_user_id</code>.
	 */
	public void setAppUserId(Long value) {
		set(2, value);
	}

	/**
	 * Getter for <code>travel.app_user_id</code>.
	 */
	public Long getAppUserId() {
		return (Long) get(2);
	}

	/**
	 * Setter for <code>travel.updated</code>.
	 */
	public void setUpdated(LocalDateTime value) {
		set(3, value);
	}

	/**
	 * Getter for <code>travel.updated</code>.
	 */
	public LocalDateTime getUpdated() {
		return (LocalDateTime) get(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row4<Long, String, Long, LocalDateTime> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	@Override
	public Row4<Long, String, Long, LocalDateTime> valuesRow() {
		return (Row4) super.valuesRow();
	}

	@Override
	public Field<Long> field1() {
		return Travel.TRAVEL.ID;
	}

	@Override
	public Field<String> field2() {
		return Travel.TRAVEL.NAME;
	}

	@Override
	public Field<Long> field3() {
		return Travel.TRAVEL.APP_USER_ID;
	}

	@Override
	public Field<LocalDateTime> field4() {
		return Travel.TRAVEL.UPDATED;
	}

	@Override
	public Long component1() {
		return getId();
	}

	@Override
	public String component2() {
		return getName();
	}

	@Override
	public Long component3() {
		return getAppUserId();
	}

	@Override
	public LocalDateTime component4() {
		return getUpdated();
	}

	@Override
	public Long value1() {
		return getId();
	}

	@Override
	public String value2() {
		return getName();
	}

	@Override
	public Long value3() {
		return getAppUserId();
	}

	@Override
	public LocalDateTime value4() {
		return getUpdated();
	}

	@Override
	public TravelRecord value1(Long value) {
		setId(value);
		return this;
	}

	@Override
	public TravelRecord value2(String value) {
		setName(value);
		return this;
	}

	@Override
	public TravelRecord value3(Long value) {
		setAppUserId(value);
		return this;
	}

	@Override
	public TravelRecord value4(LocalDateTime value) {
		setUpdated(value);
		return this;
	}

	@Override
	public TravelRecord values(Long value1, String value2, Long value3,
			LocalDateTime value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TravelRecord
	 */
	public TravelRecord() {
		super(Travel.TRAVEL);
	}

	/**
	 * Create a detached, initialised TravelRecord
	 */
	public TravelRecord(Long id, String name, Long appUserId, LocalDateTime updated) {
		super(Travel.TRAVEL);

		setId(id);
		setName(name);
		setAppUserId(appUserId);
		setUpdated(updated);
	}
}
