/* Generated By:JavaCC: Do not edit this line. VCalRuleParserConstants.java */
package ch.ess.cal.vcal.ruleparser;

public interface VCalRuleParserConstants {

  int EOF = 0;
  int DIGIT = 5;
  int DIGITS = 6;
  int PLUS = 7;
  int MINUS = 8;
  int ENDDATE = 9;
  int HASH = 10;
  int WEEKDAY = 11;
  int LASTDAY = 12;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<DIGIT>",
    "<DIGITS>",
    "\"+\"",
    "\"-\"",
    "<ENDDATE>",
    "\"#\"",
    "<WEEKDAY>",
    "\"LD\"",
    "\"D\"",
    "\"W\"",
    "\"MP\"",
    "\"MD\"",
    "\"YM\"",
    "\"YD\"",
  };

}
